### ISSUE TITLE
The link https://downloads.experiencecloud.adobe.com/content/dam/general/public/aemcloud is invalid

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#1]
Issue in help/implementing/deploying/overview.md and help/implementing/dispatcher/overview.md

The download link to the AEM/Dispatcher SDK (https://downloads.experiencecloud.adobe.com/content/dam/general/public/aemcloud) leads to a 404, while the main page at https://downloads.experiencecloud.adobe.com/content/software-distribution/en/general.html works but no longer exposes the AEM SDK.

**Comment by sarchiz** [comment]
Thanks for reporting this. The link has been updated.
