### ISSUE TITLE
[Redacted]

### ISSUE THREAD

**Issue by chekurisriharsha** [AdobeDocs/experience-manager-cloud-service.en#100]
Issue in /help/implementing/cloud-manager/managing-ssl-certifications/introduction.md

Issue Description:

[Redacted]

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This is being tracked with CQDOC-20395.

**Comment by bohnertchris** [comment]
There is no change needed to the documentation at this time. Please see CQDOC-20395 for details.
