### ISSUE TITLE
Amend the "Create blueprint configuration" paragraph 

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-cloud-service.en#101]
Issue in ./help/sites-cloud/administering/msm/creating-live-copies.md

In AEM Cloud service, it is not possible to create a blueprint via the UI 
See (1) "MSM Blueprint and custom MSM roll-out configurations must be installed from Git via the CI/CD pipeline" and (2)

The paragraph "Create blueprint configuration" should be modified or removed

(1) https://experienceleague.adobe.com/docs/experience-manager-cloud-service/release-notes/aem-cloud-changes.html?lang=en#apps-libs-immutable
(2) https://jira.corp.adobe.com/browse/CQ-4318208

[Logged By Support]

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @clatimier. The features are still available on local instances, so we added as section explaining that for production these configs need to be deployed via CI/CD pipeline, but left the content for developers working and testing locally.

Fixed in commit 61665f4
