### ISSUE TITLE
Content Copy feature [redacted]

### ISSUE THREAD

**Issue by chekurisriharsha** [AdobeDocs/experience-manager-cloud-service.en#101]
Issue in /docs/experience-manager-cloud-manager/content/using/content-copy.html

[Redacted]

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
This issue is raised against the AEMaaCS repo, but the page link is for Cloud Manager.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This is being tracked with CQDOC-20396.

**Comment by bohnertchris** [comment]
The link cited is regarding the documentation for Cloud Manager, not AEM as a Cloud Service.

https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/using/content-copy.html

The content copy feature is available for AMS as documented in the link above. This feature is not available for AEM as a Cloud Service.
