### ISSUE TITLE
Completing the IMS Configuration in AEM section is incorrect

### ISSUE THREAD

**Issue by pdimarco** [AdobeDocs/experience-manager-cloud-service.en#102]
Issue in ./help/sites-cloud/integrating/integration-adobe-target-ims.md

the image used to show the IMS Technical Account Configuration should not be using the Authorization Server URL with the API Key appended. Currently you show the URL as https://ims-na1.adobelogin.com/c/cr5d06cfddba4e309add6d56d33dd50f

This is not correct. It should be only the base URL https://ims-na1.adobelogin.com. I suspect the configuration will append the API Key for you. I spent a lot of time trying to understand why my connection would not pass the Health Check. By using only the base URL, it passed the health check

![image](https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/65278/913f3371-a0ff-4391-a10d-749164a73b09)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we have made the adjustments.
Closing this issue now.
