### ISSUE TITLE
Variable Naming: Prevent name clashes with internal environment variables

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#103]
Issue in ./help/implementing/deploying/configuring-osgi.md

The variables defined by AEMaaCS and the customization must not have the same name. Therefore either provide a list of reserved names (used by AEMaaCS internally) or come up with a naming schema which prevents name clashes with the internal environment variables.

**Comment by justinedelson** [comment]
Additionally, such a list of non-overridable environment variable names should be published to docs in a machine readable form so that tools (e.g. aio-cli-plugin-cloudmanager) can leverage that list.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kwin** [comment]
Although it has been clarified in https://github.com/AdobeDocs/experience-manager-cloud-service.en/commit/7baacc953c88e1beb13be9878b635b6e5273dea2 that all internal environment variables are supposed to start with "INTERNAL" I don't see it reflected in either https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2021.6.5382.20210602T190018Z-210527/aem-sdk-api-2021.6.5382.20210602T190018Z-210527-aem-publish-sdk.slingosgifeature or https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2021.6.5382.20210602T190018Z-210527/aem-sdk-api-2021.6.5382.20210602T190018Z-210527-aem-author-sdk.slingosgifeature. 
They contain a lot of OSGi configuration referencing internal environment variables and not a single one starts with "INTERNAL".

**Comment by aheim0** [comment]
Thanks for highlighting this - certain details have already been updated. See CQDOC-17787 for full details and further steps if required.
Closing this issue.
