### ISSUE TITLE
Development Environments

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#104]
Issue in ./help/implementing/deploying/aem-version-updates.md
This document needs to explicitly state that CI/CD only applies to Prod And Stage environments and that Dev and QA environments will have to be upgraded manually, and either create or link to a doc that shows how customers can tell if/when a release is available, what the schedule is, and how to manually upgrade their dev/QA environments.
Label:DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @alisonasanchez.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This issue was addressed with commit 8355c8e.
