### ISSUE TITLE
Path Browser Limitation

### ISSUE THREAD

**Issue by dcreaadobe** [AdobeDocs/experience-manager-cloud-service.en#106]
Issue in ./help/assets/use-assets-across-connected-assets-instances.md

Dear Team,
[Redacted] usage of path browser in authoring components does not support connected assets. I would suggest adding this limitation in the corresponding section https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/admin/use-assets-across-connected-assets-instances.html?lang=en#tip-and-limitations

thank you

**Comment by bohnertchris** [comment]
Thank you for raising this, @dcreaadobe.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kkour06** [comment]
Limitation added and pushed live at
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/admin/use-assets-across-connected-assets-instances.html
