### ISSUE TITLE
Add info on personas in the Introduction

### ISSUE THREAD

**Issue by ptager** [AdobeDocs/experience-manager-cloud-service.en#108]
Issue in ./help/implementing/developing/headless-journey/overview.md

I would suggest calling out in the Introduction that the current documentation is tailored for the Developer persona, among other personas that will be targeted later on. Alternatively, we could highlight which of the topics are for all personas, and which ones are more specific for the Developer persona until we'll develop additional journeys for the other personas.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @ptager.

In addition to mentioning the developer in the page title and introduction paragraphs, I have added a section called **Audience** which makes this more explicit. I also mention forthcoming journeys for the additional personas.

Addressed in commit 0ed8e73.
