### ISSUE TITLE
Move Environment Across Region

### ISSUE THREAD

**Issue by suchawla1989** [AdobeDocs/experience-manager-cloud-service.en#109]
Issue in ./help/journey-sites/demos-add-on/create-program.md

A note could be added for users to be catiuos while selecting the region during the creation of the environment. As once the environment is created in a region it can't be moved to other region. 

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thank you for the suggestion. We will consider.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
It was never possible to choose the region for dev environments that are automatically created for sandbox programs. In the demos add-on journey, we use the automatically created dev environment in order to keep the example as simple as possible. Closing issue since there is no update needed.
