### ISSUE TITLE
Make using APIs another step

### ISSUE THREAD

**Issue by ptager** [AdobeDocs/experience-manager-cloud-service.en#109]
Issue in ./help/implementing/developing/headless-journey/getting-started.md

Suggest moving this sentence to another bullet: APIs can then be called to retrieve this content

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Good suggestion, @ptager. Thank you.

This was addressed in commit 0ed8e73.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC
