### ISSUE TITLE
Step 2 in 'Using DocuSign with an adaptive form' tutorial is unclear - where do you clone repository?

### ISSUE THREAD

**Issue by cjreinhardt** [AdobeDocs/experience-manager-cloud-service.en#11]
Issue in ./help/forms/integrate-docusign-adaptive-forms.md

As someone new to working with archetypes, step 2 in this tutorial is unclear:  https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/forms/integrate-docusign-adaptive-forms.html?lang=en

> 2. Clone the aem-forms-samples repository. This repository contains custom submit action for DocuSign and configuration details to connect with the DocuSign server.

What directory would you clone the sample repository into? The archetype directory you created in step 1?

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by singhkh** [comment]
@cjreinhardt, You can clone from https://github.com/adobe/aem-forms-docusign-sample. Let us know if you face any issues with cloning.

**Comment by guillaumecarlino** [comment]
Closing issue. Please create a new issue if there is still an open question.
