### ISSUE TITLE
Watermarking Documentation is incorrect

### ISSUE THREAD

**Issue by kaushalmall** [AdobeDocs/experience-manager-cloud-service.en#11]
Issue in help/assets/add-watermark-to-assets.md

This page refers to updating the DAM Update Asset Workflow which doesn't exist in Cloud Service

**Comment by ashishguptaiitb** [comment]
Thanks Kaushal. I confirmed internally and have removed this functionality. I am closing this ticket as all mentions are removed. If you see the issue again, do let me know and we shall revisit.
