### ISSUE TITLE
Network infrastructure Note

### ISSUE THREAD

**Issue by suchawla1989** [AdobeDocs/experience-manager-cloud-service.en#110]
Issue in ./help/security/configuring-advanced-networking.md

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking.html?lang=en#configuring-flexible-port-egress-provision

Note : Network infra should be created in the same region in which the environment is created.

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
Thanks for the suggestion, but this is documented in the API docs, which are listed from the same section. https://developer.adobe.com/experience-cloud/cloud-manager/reference/api/#tag/Network-infrastructure/operation/createNetworkInfrastructure

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC
