### ISSUE TITLE
AEMaaC Assets documentation missing reference to publisher

### ISSUE THREAD

**Issue by riosmart** [AdobeDocs/experience-manager-cloud-service.en#110]
Issue in ./help/assets/asset-microservices-overview.md

The customer was confused since in their AEMaaC assets Admin Console it shows permissions for their publisher instance which should not exist for an assets-only implementation. 

Documentation has no mention of the publisher instance in the architecture overview. 

<img width="586" alt="AEM Asset as a Cloud Instances (1)" src="https://user-images.githubusercontent.com/71282553/118846725-021f9d00-b89b-11eb-86ad-a13eeddc2e2b.PNG">

**Comment by riosmart** [comment]
Was unaware that filing a github bug also opens a JIRA. I seperately opened a more qualified JIRA -> https://jira.corp.adobe.com/browse/CQDOC-17948. Feel free to close this one if not needed.

**Comment by ashishguptaiitb** [comment]
Thanks @riosmart . I am attending to CQDOC-17948 issue.
