### ISSUE TITLE
Clarify where the dist is deployed to

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#113]
Issue in ./help/implementing/developing/introduction/developing-with-front-end-pipelines.md

Currently it states

> The content of the dist folder is what is ultimately deployed to AEM as a Cloud Service from the Cloud Manager pipeline.

Where exactly is it deployed to? I guess it is not AEM itself but rather some dedicated server which is hooked up to the CDN (next to AEM). Please clarify that a bit.

**Comment by kwin** [comment]
A hint in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/overview/architecture.html?lang=en#runtime-architecture would be helpful as well.

**Comment by guillaumecarlino** [comment]
Thank you for reporting this @kwin . We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
We have added some more detail about the FEB contract in commit 3d17b94.
