### ISSUE TITLE
info at /content/operations/replication.html?lang=en#publish-content-tree-workflow is misleading

### ISSUE THREAD

**Issue by rogerblanton** [AdobeDocs/experience-manager-cloud-service.en#12]
Docs specify this:

Do not modify or invoke the original model. Instead, make sure to first copy the model and then modify or invoke that copy.

However, the Publish Content Tree Workflow is not modifiable, and "copying" the workflow results in another un editable workflow as it is copied with the "isImmutable=true" property intact. Perhaps some more elaboration is needed here instructing users to remove this property.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Updates made, and published.
Closing issue now.
