### ISSUE TITLE
Incorrect screenshot

### ISSUE THREAD

**Issue by estange** [AdobeDocs/experience-manager-cloud-service.en#122]
Issue in [./help/assets/assets-insights.md](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/manage/assets-insights.html)

> In the Page Tracker section, step #1 has an incorrect screenshot. It would be helpful to include a screenshot for step #3 so people can see the code.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by vishabhguptaadobe** [comment]
The article is updated with correct screenshot and sample code for Page Tracker.
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/manage/assets-insights.html#page-tracker 

Jira issue is Closed: https://jira.corp.adobe.com/browse/CQDOC-18045
