### ISSUE TITLE
Assets - provide more details for upload step if more than one URI is provided

### ISSUE THREAD

**Issue by kmurugulla** [AdobeDocs/experience-manager-cloud-service.en#123]
Issue in [./help/assets/developer-reference-material-apis.md](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/admin/developer-reference-material-apis.html)
{quote}The documentation in the Upload Step states as follows

"If more than one URI is provided, the client splits the binary into parts and make **POST** request of each part to each URI, in order. "

But when tried with two simple assets ( png , jpg) using Postman as client , I had to submit the "PUT" requests rather than "POST" requests.

Can we please update the document with a sample demo using postman ? ( Attaching the collection that I used and rename the extension to .json to import )
{quote}
[AEM Assets HTTP API.postman*collection.txt](https://github.com/AdobeDocs/experience-manager-cloud-service.en/files/6611023/AEM.Assets.HTTP.API.postman*collection.txt)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by ashishguptaiitb** [comment]
The correction is made in the docs after checking with engineering. I'm closing this ticket. Thanks @kmurugulla  for this bug.
