### ISSUE TITLE
Impossible to Add RequestHeaders (X-Forwarded-Proto)

### ISSUE THREAD

**Issue by mirkomanga** [AdobeDocs/experience-manager-cloud-service.en#124]
Issue in ./help/commerce-cloud/configuring/custom-http-headers.md
In this md at point 1. Go to the Cloud Service configuration page in Tools -> Cloud Services -> CIF Configuration
refer to an unexisting path!  In AEMaaCS istance Tools -> Cloud Services there's no occurrence of CIF Configuration console!
How can i deal with redirect managed in dispatcher rewrite.rules? Each of them move  from incoming https to http then publisher change it to https again, pooring our SEO score! I followed this tutorial: https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-16936.html?lang=en configuring dispatcher 
		**RequestHeader set X-Forwarded-Proto "https"**
without any kind of result! 
and reading this guide, well....I found out an unappliable solution! even if article was Last Updated: June 19, 2023....
Thanks & regards

**Comment by raimanS** [comment]
@mirkomanga Thank you for opening this issue. We will investigate.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
@mirkomanga, sorry I just stumbled upon this issue. The page you are referring to is specific for Commerce customers, while you seem to have dispatcher issues.
I suggest you open a support ticket with details about your AEM implementation and specificities.
