### ISSUE TITLE
only 2048-bit length private keys are currently supported

### ISSUE THREAD

**Issue by rsaraf-adobe** [AdobeDocs/experience-manager-cloud-service.en#126]
Issue in ./help/implementing/cloud-manager/managing-ssl-certifications/add-ssl-certificate.md

Please check with the technical team and add a note: 

Note: only 2048-bit length private keys are currently supported

**Comment by raimanS** [comment]
@rsaraf-adobe  Thank you for opening this issue. We will investigate.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This information is already provided in this document.
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/manage-ssl-certificates/introduction.html#requirements
I have cross-referenced it explicitly in the cited document in commit 89e1cce.
