### ISSUE TITLE
Mention removal of Product Photoshoot Workflow

### ISSUE THREAD

**Issue by riosmart** [AdobeDocs/experience-manager-cloud-service.en#126]
Issue in [./help/assets/assets-cloud-changes.md](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/assets-cloud-changes.html)

> The reason for the workflow not being available are dependencies on the older commerce implementation which is not available as part of CS.

**Comment by ashishguptaiitb** [comment]
Hi @riosmart , do you mean the 'DAM Asset Update' or some other workflow?

**Comment by riosmart** [comment]
Hi @ashishguptaiitb referring to the Product Photoshoot workflow which is included in the OOTB On-Premise version.

More details here -> https://jira.corp.adobe.com/browse/CQ-4326205

**Comment by ashishguptaiitb** [comment]
Got it @riosmart . I shall find out more about it and address it. My bad, that I read just the comment part.

**Comment by riosmart** [comment]
@ashishguptaiitb thanks!

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by ashishguptaiitb** [comment]
Hi @riosmart we've updated the parity article about lack of prod. photo shoot template in CS and also removed the photo shoot template mentions in AEM Projects docs. I'm closing this ticket.
