### ISSUE TITLE
Adobe deprecating JWT authentication - can the OAuth2.0 be applied for the integration?

### ISSUE THREAD

**Issue by decaroa** [AdobeDocs/experience-manager-cloud-service.en#127]
Good day team.
The [article ](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/sites/integrations/integration-adobe-target-ims.html?lang=en) suggests the configuration of the JWT based authentication.

The JWT auth has now been deprecated by Adobe, and the OAuth2.0 is now recommended, as described in [this article](https://developer.adobe.com/developer-console/docs/guides/authentication/JWT/):

"The Service Account (JWT) credentials have been deprecated in favor of the OAuth Server-to-Server credentials. Your applications using the Service Account (JWT) credentials will stop working after Jan 1, 2025. You must migrate to the new credential by Jan 1, 2025, to ensure your application continues functioning."

Can the OAuth2.0 be applied for the AEM and Target integration?

Issue in ./help/sites-cloud/integrating/integration-adobe-target-ims.md

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@decaroa 

We have just been informed by RnD that (in relation to this feature) "Currently, the support for OAuth server to server isn't available in AEM, so we will continue to use the Service Account (JWT) credentials.".
The documentation will be updated as soon as appropriate.
We hope that helps.

Closing this issue.
