### ISSUE TITLE
Wrong link to Cloud Manager Documentation

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/experience-manager-cloud-service.en#127]
Issue in ./help/operations/home.md
The Cloud Manager Documentation link in the Other Experience Manager Resources section points to the wrong document, [Navigate to Cloud Manager](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/onboarding/what-is-required/navigate-to-cloud-manager.html?lang=en) rather than to the root of Cloud Manager Documentation

**Comment by anujkapo** [comment]
Thanks @dburwitz. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. The structure of the doc set has changed recently, so the link has been updated accordingly.
Closing issue.
