### ISSUE TITLE
Link to "Cloud Configurations" is broken

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#129]
Issue in ./help/implementing/developing/configurations.md

Link to "Cloud Configurations" is broken

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this.
The link currently points back to itself. As there are multiple possible targets, with the possibility of more being added, I've removed the link and left the text with an extension.
Closing this issue now.
