### ISSUE TITLE
Typo in ./help/commerce-cloud/introduction.md

### ISSUE THREAD

**Issue by nikolazic** [AdobeDocs/experience-manager-cloud-service.en#130]
Issue in ./help/commerce-cloud/introduction.md

> reate once, and publish everywhere

Should be 

> Create once, and publish everywhere

**Comment by anujkapo** [comment]
Thanks, @nikolazic. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - the typo has been corrected.
Closing issue.
