### ISSUE TITLE
deleting a Translation Integration Configuration

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#131]
Issue in ./help/journey-sites/translation/configure-connector.md
The document tells you how to create a translation configuration, but not how to delete.
Page: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/sites/administering/reusing-content/translation/sites/configure-connector.html

**Comment by raimanS** [comment]
@alisonasanchez Thanks for opening this issue. We will look into it.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC
