### ISSUE TITLE
Role Definition - Responsibility of a Network Administrator seems incorrect

### ISSUE THREAD

**Issue by lingeshvel** [AdobeDocs/experience-manager-cloud-service.en#132]
Issue: Role responsibility for Network Administrator seems incorrect(highlighted below in bold). Defining UX design for the organisation is not responsibility of Network Administrator and needs correction. 

Current:
Responsible for configuring the player and typically manage the entire deployment for an AEM Screens deployment. **Defines user experience design (style, layout, branding) as per organizational requirements** and creates project structure and channels.

**Comment by bohnertchris** [comment]
Thank you for reporting this issue, @lingeshvel. There is no link to the affected page in the issue. Can you please tell us where this error occurs?

**Comment by bohnertchris** [comment]
Closing this issue due to lack of response. If you feel that documentation still needs updating, please create a new issue.
