### ISSUE TITLE
properties.xml

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#134]
Issue in ./help/operations/indexing.md
You say that a properties.xml file is needed, but we need a sample file or you need to tell us how to get that file.

**Comment by raimanS** [comment]
@alisonasanchez Thanks. We will investigate.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Updates have been made and will be published soon.
Closing this issue.
