### ISSUE TITLE
no option to assign product profile to API credentials

### ISSUE THREAD

**Issue by deepankarcouncil** [AdobeDocs/experience-manager-cloud-service.en#136]
Issue in ./help/sites-cloud/integrating/integration-adobe-target-ims.md

In - **Assigning privileges to the Integration**

section, the doc asks to 

Select API Credentials, then the required integration configuration.

Select Editor as the Product Role; instead of Observer.

But in admin console, there is no option to assign product profile to API credentials

<img width="960" alt="image" src="https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/138552340/ca3f8aac-e2be-4f54-9c10-a7302334e2f2">

is this a document issue? Or is it due to a technical issue in the IMS org?

**Comment by guillaumecarlino** [comment]
Thank you for opening this issue. We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This page has been removed and the content has been rewritten. It can now be found under: 
- https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/security/setting-up-ims-integrations-for-aem-as-a-cloud-service

We hope that helps. Closing this issue now, please open a new issue if further changes are required.
