### ISSUE TITLE
Service Account JWT in deprecated, but there are no instructions on how to configure OAuth configuration 

### ISSUE THREAD

**Issue by deepankarcouncil** [AdobeDocs/experience-manager-cloud-service.en#137]
Issue in ./help/sites-cloud/integrating/integration-adobe-target-ims.md

Adobe I/O developer console says that Your Service Account (JWT) credential has been deprecated. 

And 

Your Service Account (JWT) credential will stop working after January 1, 2025. 
 
in big bold letters. But amusingly (but not surprisingly knowing how disjointed the teams are) no instructions are provided on the page on how to configure Ouath configuration for integration with target.

Please provide instruction for Ouath configuration integration with target.

 Or ask the Adobe I/O team to not deprecate JWT credentials

<img width="580" alt="image" src="https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/138552340/e48cc3ef-95a0-41f1-aad1-62e0d25675ea">

**Comment by guillaumecarlino** [comment]
Thank you for opening this issue. We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this. In the meantime the page has been updated with a Caution about the current status of JWT and OAuth.

Closing issue.
