### ISSUE TITLE
Content: "left" instead of "right"

### ISSUE THREAD

**Issue by grobkonzept** [AdobeDocs/experience-manager-cloud-service.en#138]
Issue in ./help/implementing/universal-editor/authoring.md

In the sentence under the H3 title "Component Rail", it is stated that: 
"The component rail is always present along the **left** side of the editor. "
It should be: 
"The component rail is always present along the **right** side of the editor. "

Keep up the good work, 
Michael

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this. The change has been made and will be published soon.

Closing issue.
