### ISSUE TITLE
please include rde, author.rde & publish.rde as runmodes provided OOTB

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-cloud-service.en#139]
Issue in ./help/release-notes/aem-cloud-changes.md

Issue Description: Under Custom runmodes are not allowed, please include rde, author.rde & publish.rde as additional runmodes to align with https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/deploying/overview.html?lang=en#runmodes

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Removed duplicate information from `aem-cloud-changes.md` and referenced `deploying/overview.md` directly in commit 89e1cce.
