### ISSUE TITLE
Troubleshooting hyperlink links to wrong page

### ISSUE THREAD

**Issue by Chhavi1991Gupta** [AdobeDocs/experience-manager-cloud-service.en#14]
Issue in ./help/sites-cloud/integrating/experience-fragments-target.md

1. If you cannot connect to Target, see the [troubleshooting](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/sites/integrations/experience-fragments-target.html?lang=en#troubleshooting-target-connection-problems) section.
2. Click on troubleshooting, and this would not go anywhere and stay on the same page

I believe the correct hyper link: https://experienceleague.adobe.com/docs/target/using/troubleshoot/troubleshooting-target.html?lang=en

**Comment by guillaumecarlino** [comment]
Thanks for reporting.
Unfortunately, the link you're suggesting is not relevant. There used to be a section which does not apply anymore so I removed the link entirely.
