### ISSUE TITLE
rde commands are not working as expected

### ISSUE THREAD

**Issue by yogiraj-mahajan** [AdobeDocs/experience-manager-cloud-service.en#140]
Issue in ./help/implementing/developing/introduction/rapid-development-environments.md

C:\Users\Yogesh>**aem rde status**
'aem' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Yogesh>**aio rde status**
 »   Warning: rde status is not a aio command.
Did you mean aem rde status? [y/n]: y
Info for cm-p34580-e1156206
Environment: Ready
- Bundles Author:
- Bundles Publish:
- Configurations Author:
- Configurations Publish:

**Comment by bohnertchris** [comment]
Thank you for reporting this, @yogiraj-mahajan. However I am unclear what the problem is. Nowhere in the cited document do we provide the commands `aem rde status` or `aio rde status`.

Could you please be a bit more specific what correction or change you would like to see in the documentation?

**Comment by yogiraj-mahajan** [comment]
Thanks for the response , I revalidated it , it is working as expected , may be I overlooked it . Thanks !

**Comment by bohnertchris** [comment]
Thanks for the confirmation!
