### ISSUE TITLE
Notification Configurations have changed

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#141]
Issue in ./help/implementing/cloud-manager/notifications.md
When I click on the gear icon, and expand one of the options, it looks like this: 
<img width="1189" alt="image" src="https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/98857862/ebc48f84-cbf8-4e7d-a8ef-c78097e155ff">

The docs need to be updated for the updated UI.
Additionally, we need to know what kind of permissions are needed in order to make changes on this window.

**Comment by bohnertchris** [comment]
Thank you for pointing this out, @alisonasanchez. We will update the page.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
The documentation was updated with commit e2658df.
