### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#142]
Issue in ./help/implementing/deploying/aem-version-updates.md
Can you create a section on this document which tells how and when a customer is notified of updates, and link to the page where it tells them how to manage their notifications. 
Ideally, I would want to know how far in advance is a customer notified that a feature release is available (or will be made available) for upgrade (if at all). 
Also, I'm assuming that maintenance releases are done automatically to all environments. Can you confirm in the document that maintenance releases are not available on dev first (or if they are automatically pushed to dev first, how are they notified and how far in advance.
Thanks!

**Comment by bohnertchris** [comment]
Thank you for the suggestions. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
I added links to relevant pages.
