### ISSUE TITLE
No information on domain names for author

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#143]
Issue in ./help/implementing/cloud-manager/custom-domain-names/add-custom-domain-name.md
Currently, one can only assign custom domain names to publish and preview environments and not author.
This needs to be documented.

**Comment by guillaumecarlino** [comment]
Thank you for opening this issue. We will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This is documented here.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/custom-domain-names/introduction.html#limitations
