### ISSUE TITLE
New API method is lost in the middle of a paragraph

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-cloud-service.en#147]
Issue in ./help/implementing/dispatcher/caching.md

I was speaking with a customer today and realized they had missed the new API method to explicitly invalidate the cache, "Instead, the replication flush agent should be used." This was missed because it was below the information about what does NOT work with AEM CS, and didn't have a separate paragraph. Maybe even a distinct header would be wise.

**Comment by aheim0** [comment]
Thanks for highlighting this. Changes have been made.
Closing issue.
