### ISSUE TITLE
Full URL doesn't show

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#148]
Issue in ./help/security/oauth2-support-for-mail-service.md
As per the attached screenshot, the end of the URL for step 1 is cut off..... unless you change the size of your window:
<img width="1608" alt="image" src="https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/98857862/6165ee00-9f8a-414b-9d35-db5b42d20475">

**Comment by sarchiz** [comment]
Thanks for reporting this @alisonasanchez . We've updated the page - the readability should be improved.
