### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by friendlymahi** [AdobeDocs/experience-manager-cloud-service.en#150]
Issue in ./help/implementing/developing/tools/maven-plugin.md

The top note says package goal is no longer managed in this plugin since v1.0.2 and is now part of [Apache Jackrabbit FileVault Package Maven plugin.](https://jackrabbit.apache.org/filevault-package-maven-plugin/]. With this being said, [package|https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developer-tools/maven-plugin.html?lang=en#package] section should no longer be part of Content Package Maven plugin documentation. Or atleast it should be called out in a seperate section on how to use both plugins like how it was described in [Migrating From Adobe's Content Package Maven Plugin|https://jackrabbit.apache.org/filevault-package-maven-plugin/migrating.html#overview)

**Comment by guillaumecarlino** [comment]
Thanks @friendlymahi , we will review.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this. Updates have been made and will be published soon.
Closing issue.
