### ISSUE TITLE
Broken table

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#151]
Issue in ./help/implementing/developing/tools/maven-plugin.md

The table in section for goal "install" is broken
![Screenshot 2021-11-10 at 18 29 37](https://user-images.githubusercontent.com/185025/141163248-67329ae2-84a2-4924-9e13-e475cf6a958f.png)

**Comment by anujkapo** [comment]
Thanks, @kwin. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for highlighting this - the table has been fixed.
Closing this issue.
