### ISSUE TITLE
Mismatch information on async download

### ISSUE THREAD

**Issue by yann117** [AdobeDocs/experience-manager-cloud-service.en#151]
Issue in ./help/assets/download-assets-from-aem.md

The documentation states:

> Experience Manager supports large downloads with asynchronous requests. Download requests larger than 100 GB are split into multiple ZIP archives with a maximum size of 100 GB each.

This sounds completely incredible, downloading a single file of 100 Gb is not common and seems obviously a mistake.

This is probably confirmed later in the article, where the _100 GB_ becomes _100 MB_ which is much more realistic:

> Asynchronous downloads are triggered [..] If the download size is more than 100 MB

Yannick
AEM Support-EMEA
(sorry I forgot about the tag)

**Comment by guillaumecarlino** [comment]
Thanks, we will check.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kkour06** [comment]
The information has been updated and available live at https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/assets/manage/download-assets-from-aem.html?lang=en#:~:text=Download%20requests%20larger%20than%20100%20GB%20are%20split%20into%20multiple%20ZIP%20archives%20with%20a%20maximum%20size%20of%20100%20MB%20each 

cc: @anujkapo
