### ISSUE TITLE
AEM Cloud Service Apache/Dispatcher tier’s mod_proxy directive doesn’t work

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-cloud-service.en#155]
Issue in ./help/security/configuring-advanced-networking.md

The steps described for the AEM Cloud Service Apache/Dispatcher tier’s mod_proxy directive doesn't work.

1. Generate a project from the archetype
2. Create a custom virtual host by copying default.vhost
3. Add this line straight from the documentation [https://experienceleague.adobe.com/docs/experience-manager-cloud-service/security/configuring-advanced-networking.html%3Flang%3Dde#flexibl[…]routing]

```
ProxyRemote "http://example.com" "http://${AEM_HTTP_PROXY_HOST}:${AEM_HTTP_PROXY_PORT}"
ProxyPass "/somepath" "http://example.com"
ProxyPassReverse "/somepath" "http://example.com"
```

4. The validation fails at
```
[Thu Nov 25 04:00:02.125510 2021] [core:warn] [pid 1:tid 140122914822984] AH00111: Config variable ${AEM_HTTPS_PROXY_HOST} is not defined
[Thu Nov 25 04:00:02.126196 2021] [core:warn] [pid 1:tid 140122914822984] AH00111: Config variable ${AEM_HTTPS_PROXY_PORT} is not defined
AH00526: Syntax error on line 63 of /etc/httpd/conf.d/enabled_vhosts/default-with-proxy.vhost:
ProxyRemote: Bad syntax for a remote proxy server (bad port number)
```

5. If the ${AEM_HTTPS_PROXY_PORT} is replaced by a real value like 3128, the warnings for ${AEM_HTTP_PROXY_HOST} is still thrown, but the validation is successfull.

Please see https://jira.corp.adobe.com/browse/SKYOPS-21877

**Comment by bohnertchris** [comment]
Thank you for reporting this, @swaroop61. We will have a look.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC
