### ISSUE TITLE
Cloud Manager Release Notes 2023.11.0 overdue

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#155]
Issue in ./help/implementing/cloud-manager/release-notes/current.md

According to the description 

> The next release is planned for 2 November 2023.

Was there a delay? Can you adjust the text with a new ETA for Cloud Manager 2023.11.0?

**Comment by anujkapo** [comment]
Thanks, @kwin. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Hello, @kwin. Indeed there was a delay. The release went out yesterday and the release note now reflect that.
