### ISSUE TITLE
Add a link to the configuration tutorial

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-cloud-service.en#159]
Issue in ./help/security/configuring-advanced-networking.md

In addition to this documentation, the technical enablement group created tutorials to demonstrate how to perform these configurations. It would be beneficial to redirect the customers to these tutorials. 
Could the page (1) containing these tutorials be referenced?

(1) https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/networking/advanced-networking.html?lang=en

[Logged by Support]

**Comment by anujkapo** [comment]
Thanks, @clatimier. We will add the link.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@clatimier 

There is already a link to the suggested page. See the info box at the top of the page:
- https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking.html?lang=en 

Closing issue.
