### ISSUE TITLE
 Service Level Terms (SLT)  vs  Service Level Target (SLT) 

### ISSUE THREAD

**Issue by tomotomoyb4** [AdobeDocs/experience-manager-cloud-service.en#159]
Issue in ./help/edge/overview.md

SLT is not Service Level Terms. 
So could you please modify the following?
<current>
 Service Level Terms (SLT) 
<suggestion>
 Service Level Target (SLT)

**Comment by aheim0** [comment]
Thanks for raising this - we will address.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Changes have been made, and will be published soon.

Closing this issue.
