### ISSUE TITLE
The steps to get the Adobe I/O Cloudmanager Interface is missing in the documentation

### ISSUE THREAD

**Issue by adisharm** [AdobeDocs/experience-manager-cloud-service.en#16]
The documentation mentions an Adobe I/O Cloudmanager Interface but does not describe at all how to get that. Without that the documentation does not provide many insights.

**Comment by raimanS** [comment]
Thank you for opening the issue. Can you please specify the page you are referring to?

**Comment by adisharm** [comment]
Hi @raimanS , Sorry I reached here by clicking a "Report issue" link from the page so thought that should have been captured. Anyways, this is the page I was referring too. https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/using-cloud-manager/manage-logs.html

**Comment by raimanS** [comment]
Thank you for the additional information . We'll follow up with the update.

**Comment by jyotikas** [comment]
@adisharm, links to Cloud Manager API and Adobe I/O CLI is now included to the page. Please refer to the link below:
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/using-cloud-manager/manage-logs.html#resources
