### ISSUE TITLE
The documentation for targeted config deployment is confusing to the customer

### ISSUE THREAD

**Issue by chvijaydravid** [AdobeDocs/experience-manager-cloud-service.en#160]
Issue in ./help/implementing/cloud-manager/configuring-pipelines/configuring-non-production-pipelines.md

![image (2)](https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/16907182/1a71706e-42af-465f-8bdc-c8c54a0ad88f)
![image (4)](https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/16907182/3a2a15c8-5f89-42c5-b3b1-926ea9f70c8b)

The documentation says there can be a targeted deploy for config. So the customer is thinking that they could deploy osgi config changes and maintenance task changes as part of this targeted config deploy. I had one reach out to me and had feedback about the documentation being confusing.

So my request is to update the document to clarify it better about what we mean by targeted config deploy.

Thanks,
Vijay

**Comment by aheim0** [comment]
Thank you for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit 263dab9.
