### ISSUE TITLE
Incorrect description of packages being installed.

### ISSUE THREAD

**Issue by bhellema** [AdobeDocs/experience-manager-cloud-service.en#163]
Issue in ./help/implementing/developing/introduction/repository-structure-package.md at https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developing/repository-structure-package.html?lang=en#multi-code-package-use-case 

The sentence 

> If a package-level dependency is not established from code package B on code package A, code package B may deploy first into /apps/a. It would then be followed by code package B, which deploys into /apps/a. The result is a removal of the previously installed /apps/a/b.

I believe should read:

> If a package-level dependency is not established from code package B on code package A, code package B may deploy first into /apps/a. It would then be followed by code package A, which deploys into /apps/a. The result is a removal of the previously installed /apps/a/b.

If package B is installed first THEN package A, that would be the issue, but in the sentence, it reads that B is installed twice.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Updates have been made, they will be published soon. Thanks for raising this.
