### ISSUE TITLE
Terminology - Universal Editor vs Page Editor

### ISSUE THREAD

**Issue by holmsj** [AdobeDocs/experience-manager-cloud-service.en#164]
Issue in ./help/commerce-cloud/commerce-journeys/aem-commerce-content-author/getting-started.md

This document refers to CIF authoring in the "Universal Editor", which seems to in reality be the [Page Editor](https://experienceleague.adobe.com/docs/experience-manager-learn/sites/page-authoring/page-editor-feature-video-use.html?lang=en).

This may cause confusion, especially with the introduction of a differing authoring method external to AEM called [Universal Editor](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/universal-editor/introduction.html?lang=en).

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks for reporting @holmsj , you were right. Updates will be live soon.
