### ISSUE TITLE
 not available in the Admin view

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#169]
Issue in ./help/assets/assets-view-introduction.md

"The Assets view provides the following key benefits that are NOT available in the Admin view:"

Why would you point out, what is NOT available in Admin view? Or should that read "NOW"?

**Comment by anujkapo** [comment]
Hi @ackoch. That is indeed Not and not NOW. We launched Assets view last June and wanted to tell the readers what Assets view offers that Admin view doesn't. It was a Product Management and Product Marketing decision to have this article in place.
