### ISSUE TITLE
Link to "Installing and Configuring Players in Screens as a Cloud Service." is redirecting to Publishing Page

### ISSUE THREAD

**Issue by kmurugulla** [AdobeDocs/experience-manager-cloud-service.en#171]
Issue in ./help/screens-cloud/creating-content/manage-publish.md

**Comment by kmurugulla** [comment]
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/screens-as-cloud-service/create-content/manage-publish.html?lang=en

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Link will be fixed shortly.
