### ISSUE TITLE
Sample log configurations don't work

### ISSUE THREAD

**Issue by bayrakta** [AdobeDocs/experience-manager-cloud-service.en#171]
Issue in ./help/implementing/developing/introduction/logging.md

I prepared a logger according to the provided samples in the documentation. However, logs were not observed in error.log, until I appended the following OSGi configuration parameter :

"org.apache.sling.commons.log.file": "logs/error.log"

Please verify and observe this behaviour and revise all sample logging configurations.

Thank you,
Yunus Bayraktar

**Comment by guillaumecarlino** [comment]
Thanks for reporting, we will have a look.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - the updates have been made and will be published soon.
Closing issue now.
