### ISSUE TITLE
itemmodel still referenced in Attributes and Types for Universal Editor

### ISSUE THREAD

**Issue by lucianfelix** [AdobeDocs/experience-manager-cloud-service.en#173]
Issue in ./help/implementing/universal-editor/attributes-types.md

data-aue-label | Defines a custom label for a selectable item which is displayed in the editor In case itemmodel is set, the label is retrieved by way of the model
-- | --

`itemmodel` is no longer used so it should be replaced with the new prop name.

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thanks for pointing out this oversight. This has been corrected in commit 7436874.
