### ISSUE TITLE
Contradiction in copy vs table info

### ISSUE THREAD

**Issue by thedoc31** [AdobeDocs/experience-manager-cloud-service.en#176]
Issue in ./help/operations/maintenance.md

We're contradicting ourselves in the description versus what's actually in the table. 

Header states
```Adobe manages those maintenance tasks which have settings that are not configurable by customers (for example, Datastore Garbage Collection, Audit Log Purge, Version Purge). Other maintenance tasks can be configured by customers, as described in the table below.```

But down in the table below it specifically says customers can enable `Version Purge` and `Audit Log Purge`. Guessing whoever changed the copy in the table forgot to edit the header too.

**Comment by raimanS** [comment]
Thank you for opening this issue. We will look into it.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
Content updated.
