### ISSUE TITLE
Please update the note

### ISSUE THREAD

**Issue by rsaraf-adobe** [AdobeDocs/experience-manager-cloud-service.en#178]
Issue in ./help/implementing/dispatcher/caching.md

For proper Dispatcher invalidation, make sure that requests from “127.0.0.1”, “localhost”, “.local”, “.adobeaemcloud.com”, and “.adobeaemcloud.net” are all matched and handled by a vhost configuration so the request can be served. You can do this task by global matching “*” in a catch-all vhost configuration following the pattern in the reference [AEM archetype](https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/dispatcher.cloud/src/conf.d/available_vhosts/default.vhost). Or, you can ensure that the previously mentioned list is caught by one of the vhosts.

“127.0.0.1”, “localhost”, “.local”, “.adobeaemcloud.com”, and “.adobeaemcloud.net”
to 
“127.0.0.1”, “localhost”, “\**{*}*.local”, “\**{*}.adobeaemcloud.com”, and “\**.adobeaemcloud.net”

Please add * to the “.local”, “.adobeaemcloud.com”, and “.adobeaemcloud.net”

**Comment by krystiannowak** [comment]
@raimanS @froesef FYI

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by raimanS** [comment]
The note has been updated.
