### ISSUE TITLE
Contradicting information on where to include sub packages

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#18]
While it is stated in https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html#recommended-package-structure that 
> The all package is a container package that ONLY includes the ui.apps and ui.content packages as embeds. The all package must not have any content of its own, but rather delegate all deployment to the repository to its sub-packages.
Packages are now included using the Maven FileVault Package Maven plugin's embeddeds configuration , rather than the <subPackages> configuration.

it is mentioned in https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/deploying/overview.html#including-third-party that third party packages should be added via the `subPackages` configuration.

**Comment by davidjgonzalez** [comment]
Thanks for the note @kwin - the first link is correct, we can correct the latter.

**Comment by bohnertchris** [comment]
This was corrected with commit eb54d5b.
