### ISSUE TITLE
caching rules link is giving 404 error

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-cloud-service.en#181]
Issue in ./help/implementing/dispatcher/caching.md

The link in the Notes section to "caching rules" [1] is giving 404 error

[1] https://helpx.adobe.com/experience-manager/kb/find-out-which-requests-does-aem-dispatcher-cache.html

**Comment by anujkapo** [comment]
The article with the fix is available live at:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/caching.html
