### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by rrusher** [AdobeDocs/experience-manager-cloud-service.en#188]
Issue in ./help/implementing/universal-editor/field-types.md

On this page: <https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/developing/universal-editor/field-types#component-types>

In the Component Types table, the Rich Text component type is "richtext", not "rich-text".

**Comment by guillaumecarlino** [comment]
@rrusher thanks for reporting, we will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
It'll be updated shortly.
