### ISSUE TITLE
Annotations not working

### ISSUE THREAD

**Issue by vivekbd** [AdobeDocs/experience-manager-cloud-service.en#190]
Issue in ./help/implementing/cloud-manager/managing-code/github-annotations.md

We have setup the Github App and can see pipelines running on each PR. We can also see the summary of the results on Github. However the annotations doesn't seem to work. We are just seeing the link to Cloud Manager Pipeline to see the issues.

Is the document obsolete or some additional steps are required for annotations to work? I can't see any details on configuring Annotations.

**Comment by guillaumecarlino** [comment]
Thanks @vivekbd , we will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by vivekbd** [comment]
Please let me know if any further information is required from me.

**Comment by bohnertchris** [comment]
There is no additional setup. If you re having trouble with this feature, please reach out to support.

**Comment by vivekbd** [comment]
Thanks!

Just want to confirm one thing. By Support, you mean Enterprise support for Adobe Cloud or GitHub App (Please provide any available link, since I do not see any contact info in the GitHub App page)?

**Comment by bohnertchris** [comment]
Any questions about the use of the product should be raised with Adobe Experience Cloud support. https://experienceleague.adobe.com/home#support
