### ISSUE TITLE
Private Github: Possible to use in AMS Production Pipelines?

### ISSUE THREAD

**Issue by nhirrle** [AdobeDocs/experience-manager-cloud-service.en#191]
In https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/managing-code/private-repositories there is a statement that [full-stack and frontend pipelines.](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/cicd-pipelines/introduction-ci-cd-pipelines) are supportered with private github repository. 
How about AMS Production Pipelines, are they supported?

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Please see the AMS Cloud Manager documentation. https://experienceleague.adobe.com/en/docs/experience-manager-cloud-manager/content/managing-code/private-repositories

**Comment by nhirrle** [comment]
Thanks @bohnertchris . But the documentation refers to frontend and config pipeline, this is incorrect for AMS as this doesn't exist. This is why I believe it should be rechecked and updated

**Comment by bohnertchris** [comment]
I misunderstood your original query. Thank you for taking time to clarify, @nhirrle. We will fix this.

**Comment by bohnertchris** [comment]
CQDOC-21694

**Comment by bohnertchris** [comment]
Wording was updated with commit [103ae5f](https://github.com/AdobeDocs/experience-manager-cloud-manager.en/commit/103ae5f1ccff704450b9a96a28ade44460872ff1) to the Cloud Manager for AMS repo.
