### ISSUE TITLE
Non-public link in copy

### ISSUE THREAD

**Issue by Carnix** [AdobeDocs/experience-manager-cloud-service.en#193]
Issue in ./help/release-notes/release-notes-cloud/release-notes-current.md

Appears you have a link to `https://git.corp.adobe.com/AdobeDocs/experience-manager-cloud-service.en/blob/shwetad-patch-1/help/implementing/cloud-manager/content-requests.md#real-user-monitoring-for-aem-as-a-cloud-service` which isn't publicly accessible.

See link in paragraph under **New feature in Experience Manager Sites**

This is the **paragraph** in question:
![image](https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/2048465/430c7eb8-2f91-48d3-b6d5-37d9ed7b817b)

**This is the error that appears:**
![image](https://github.com/AdobeDocs/experience-manager-cloud-service.en/assets/2048465/1df533e3-03e1-45c0-a207-1dbe0449ee15)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Many thanks for raising this, the link has been corrected.
Closing issue.
