### ISSUE TITLE
Update Manage Publication documentation for Scheduled Publication - Complete button

### ISSUE THREAD

**Issue by cbCode123** [AdobeDocs/experience-manager-cloud-service.en#194]
Issue in ./help/sites-cloud/authoring/fundamentals/publishing-pages.md

This is raised to request an update in the documentation for Publishing Pages - Manage Publication - Scheduling Later.

When selecting Scheduling Later, a notification is generated with the message "Waiting for activation until the scheduled time is reached". The customer receives the notification in Inbox and the Complete button is available.

Documentation should be updated to inform customers that if they press the Complete button, this will force the workflow to be completed, hence the publication will happen without waiting until the scheduled date set in Manage Publication.

Currently, the effect of the Complete button in this notification is not documented in [1]  and customers think this is just an approval/confirmation action to acknowledge the publishing on the scheduled date, when in fact this is forcing the publishing at the moment Complete button is pressed.

[1] https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/sites/authoring/fundamentals/publishing-pages.html?lang=en#publishing-from-the-console

[Logged by support]

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thank you for this issue, but Product Management has decided that the functionality should be updated rather than documented. Hopefully the changes will be applied soon.
Closing this issue.
