### ISSUE TITLE
appears where exactly? 

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#195]
Issue in ./help/implementing/cloud-manager/custom-domain-names/add-text-record.md

This sentence:
Add _aemverification.[yourdomainname] as the Name value, and add the TXT value exactly as it appears.

Can you be more specific where the TXT value appears so we can be sure it is exact as required? Maybe a screenshot of where it appears just to be super clear.

**Comment by guillaumecarlino** [comment]
Thanks for reporting @alisonasanchez , we will review.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for reporting this. This was likely an oversight when the custom domain name documentation was broken into more manageable-sized articles and the context was lost. This was addressed in commit f108eb8.
