### ISSUE TITLE
Links are not working!

### ISSUE THREAD

**Issue by cxc38** [AdobeDocs/experience-manager-cloud-service.en#196]
Issue in ./help/assets/asset-selector.md

The link:

https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/assets/manage/asset-selector#adobe-non-app-integration

is not working.

**Comment by guillaumecarlino** [comment]
Thanks for reporting, we will investigate.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kkour06** [comment]
The interlinking has been resolved with the new bifurcation of the Asset Selector public documentation. PFA the landing page of Asset Selector https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/assets/manage/asset-selector/overview-asset-selector

cc: @anujkapo @guillaumecarlino

**Comment by guillaumecarlino** [comment]
Thanks @kkour06 , closing the issue.
