### ISSUE TITLE
Links not working for IDC reports given at the bottom of the page

### ISSUE THREAD

**Issue by lsaini** [AdobeDocs/experience-manager-cloud-service.en#196]
Issue in ./help/overview/assessing-kpis.md

[The Business Value of Adobe Experience Manager Sites](https://www.adobe.com/content/dam/acom/en/modal-offers/idc-aem-sites-q218/pdfs/22037555.en.aem.whitepaper.IDCBusinessValueAEMSites.pdf)
[The Business Value of Adobe Experience Manager Assets](https://wwwimages2.adobe.com/content/dam/acom/en/modal-offers/idc-aem-Assets-q218/pdfs/220380622.en.aem.whitepaper.IDCBusinessValueAEMAssets.pdf)

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The reports seem to have been removed from our systems, so have removed the paragraph. Changes will be published soon.
Closing this issue now.
