### ISSUE TITLE
Incorrect Maven Command

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-cloud-service.en#197]
Issue in ./help/implementing/cloud-manager/getting-access-to-aem-in-cloud/build-environment-details.md

This page says the maven command for running JaCoCo is:

> mvn --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent packageco-maven-plugin:prepare-agent package

But it should be:

> mvn --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent package

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by kwin** [comment]
There is #140 which should fix this. Unfortunately noone seems to review/merge PRs in this repo...

**Comment by bohnertchris** [comment]
This was corrected with commit c12c692.
