### ISSUE TITLE
No configmgr on cloud

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#199]
Issue in ./help/implementing/developing/tools/externalizer.md

There is no configmgr on cloud. so this cloud specific document shoudl not ask customers to go to configmgr. New instructions should be added for cloud on that section.

**Comment by raimanS** [comment]
@alisonasanchez Thank you for opening this issue.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The documentation warns that:

- As when applying any OSGi configurations for AEM as a Cloud Service, the following steps should be performed on a local developer instance and then committed to your project code for deployment.

The Web console, and configmgr, is available for a local instance.

We hope that helps; closing issue now.
