### ISSUE TITLE
Additional information should be added regarding for splunk forwarding

### ISSUE THREAD

**Issue by pstrader** [AdobeDocs/experience-manager-cloud-service.en#2]
Issue in ./help/implementing/developing/introduction/logging.md

The following location:
<https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developing/logging.html?lang=en#splunk-logs>

Under this section:
- Enabling Splunk Forwarding

In the support request, customers should indicate:
- Splunk HEC endpoint address
- The Splunk index
- The Splunk port
- The Splunk HEC token. See [this page](https://docs.splunk.com/Documentation/Splunk/8.0.4/Data/HECExamples) for more information.

**The Splunk HEC endpoint address should have some clarifications added:**
**- The endpoint address needs to be:**
**-- Publicly accessible**
**-- Have a valid SSL certificate**

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
That was published. Closing issue.
