### ISSUE TITLE
Next page link or button disappeared at the bottom of pages

### ISSUE THREAD

**Issue by OpekunAleksei** [AdobeDocs/experience-manager-cloud-service.en#201]
The next page link or button has disappeared from the bottom of pages. Previously there was a choice of going to the next page or back to the previous page.

Issue in ./help/implementing/cloud-manager/configuring-pipelines/introduction-ci-cd-pipelines.md

**Comment by bohnertchris** [comment]
Thank you for the issue, @OpekunAleksei. The previous/next page feature was introduced to the underlying documentation platform on which are docs are hosted, but was never intended or designed for AEM documentation. By its nature, AEM documentation is not linear and as such the previous/next page button was not appropriate.
