### ISSUE TITLE
disable through code

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#202]
Issue in ./help/overview/aem-cloud-service-on-unified-shell.md

According to this slack thread, it is possible to disable unified shell by setting a property on a node. This should be documented here. 

[Redacted]

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
The information has been added (under Development - and cross-referenced). See the CQDOC issue for full details.
Closing this issue.
