### ISSUE TITLE
Incorrect documentation for private dependencies

### ISSUE THREAD

**Issue by pat-lego** [AdobeDocs/experience-manager-cloud-service.en#202]
In this example, https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/create-application-project/setting-up-project.html?lang=en#password-protected-maven-repositories the CLI creates a secret variable but uses the following syntax to get variable ${env.CUSTOM_MYCO_REPOSITORY_PASSWORD}.

The true solution is to do ${secret.CUSTOM_MYCO_REPOSITORY_PASSWORD} and this is what solved the problem here: E-000613376

So the issue here is the fact that it is not documented that you can do `${env.XYZ}` when it's an environment variable and `${secret.XYZ}` when its a secret variable

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
