### ISSUE TITLE
org.apache.sling.settings is no longer deprecated since 17560

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#203]
Since release 17560 (https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/maintenance/latest) Sling Settings is no longer deprecated (GRANITE-53473: Undeprecate Sling Settings)

Compare also with https://javadoc.io/doc/com.adobe.aem/aem-sdk-api/latest/org/apache/sling/settings/SlingSettingsService.html
Please remove the entry from ./help/release-notes/deprecated-removed-features.md

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
@kwin Thanks for raising this - the updates have been made and will be published soon.
Closing issue now.

**Comment by aheim0** [comment]
Published: https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/deprecated-removed-features?#aem-apis
