### ISSUE TITLE
Dynamic Media fmt command and Smart Imaging

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#205]
Issue in ./help/assets/dynamic-media/imaging-faq.md

At the bottom: 

>**Image serving command support in Smart Imaging**
>The Image Serving commands fmt and qlt are not supported; all remaining commands are supported.

`fmt`actually is supported. At least, when I use `&fmt=png` I get a PNG and `&fmt=jpg` renders JPG. 

What I think this chapter *could* mean is something like: "*when using `fmt`this implicitly turns of smart imaging*`. To be validated with engineering.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by rickbrough** [comment]
From Sachin Bhardwaj (Computer Scientist II) check: "The documentation looks right to me. For example, both URLs below render AVIF only:

    https://dev-smartimaging.scene7.com/is/image/ADBE/AdobeStock_257024669?wid=500&hei=300&fmt=png
    https://dev-smartimaging.scene7.com/is/image/ADBE/AdobeStock_257024669?wid=500&hei=300&fmt=jpg

If the user has a URL to support the observation in their description, please have them share it with us."
