### ISSUE TITLE
Missing release Notes

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-cloud-service.en#208]
Release notes for 2022.4 and 2022.3 do not exist on the docs pages:

They are [here](https://github.com/AdobeDocs/experience-manager-cloud-service.en/tree/main/help/implementing/cloud-manager/release-notes-cloud-manager)

But they are not here:

<img width="518" alt="Release_Notes_for_Cloud_Manager_2022_5_0_in_Adobe_Experience_Manager_as_a_Cloud_Service___Adobe_Experience_Manager_and_Slack_____adobepets___AEM_Engineering" src="https://user-images.githubusercontent.com/6520270/170536737-2a010084-b044-4a46-a013-c6fb0e080fea.png">

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC
