### ISSUE TITLE
Please change "whitelist" to "allow list"

### ISSUE THREAD

**Issue by JoePearlAdobe** [AdobeDocs/experience-manager-cloud-service.en#208]
Issue in ./help/assets/dynamic-media-open-apis-overview.md

In one of the boxes on the documentation page, there is this statement: To integrate with a non-Adobe application, provide domain names to whitelist where the application is hosted.

Please change "whitelist" to "allow list" in accordance with Adobe's preference for non-offensive language.

**Comment by guillaumecarlino** [comment]
Thanks for raising this - I will update it.

**Comment by guillaumecarlino** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
This will be live soon.
