### ISSUE TITLE
Instructions mention params not found in the sample URL

### ISSUE THREAD

**Issue by vcohen-irvinecompany** [AdobeDocs/experience-manager-cloud-service.en#209]
Issue in ./help/assets/dynamic-media/dm-best-practices.md

In the section labeled **Apply Dynamic Media URL commands for effects**, the URL doesn't contain the `$shadow$` or `color` parameters mentioned in the instructions below it. The URL renders the shadow. A similar entry further below, **Drop shadow effect along the outer boundary**, shows an example URL with the correct parameters.
> • Drop shadow effect:
> To add a drop shadow effect along the subject’s boundary, edit the URL like this:
> https://s7g10.scene7.com/is/image/genaibeta/watch-silver-offer?mask=watch-silver-offer-maskps&maskUse=invert&effect=-1&pos=100,100&op_blur=75&op_grow=1&opac=25
> In this URL, the `$shadow$` parameter creates the shadow effect, and color=0,0,0 sets the shadow color to black.

**Comment by anujkapo** [comment]
Thanks, @vcohen-irvinecompany. We'll take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by rickbrough** [comment]
Fixed in DM Help dated October 23, 2024 or later. See https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/assets/dynamicmedia/dm-journey/dm-best-practices#effects-inside-the-source-image
