### ISSUE TITLE
Misleading Caution note about Brandportal IMS configs

### ISSUE THREAD

**Issue by actinium15** [AdobeDocs/experience-manager-cloud-service.en#21]
Issue in help/assets/configure-aem-assets-with-brand-portal.md

the doc at currently reads:
>Create only one valid IMS configuration. Do not create multiple IMS configurations.

This is less clear, since the two sentences seem to contradict themselves. (one suggests, “it is ok to create multiple IMS configs as long as only one of them is valid”, and the next one says “Don’t create multiple configs”. - we definitely don’t want the former message to get across, even by error)

I think it’d read better if it said:
>Create only a single IMS configuration. Do not create multiple IMS configurations.

or just a comma is added:
>Create only one, valid IMS configuration. Do not create multiple IMS configurations.

(though I think former is better)

**Comment by bohnertchris** [comment]
We appreciate the observation, @actinium15 . We will look into it.

**Comment by bohnertchris** [comment]
CQDOC-15797

**Comment by vishabhguptaadobe** [comment]
@bohnertchris  
Does the following make sense:
"Create only one, valid IMS configuration. 
Make sure that the configuration is healthy. In case, the configuration is unhealthy, delete it and create a new, healthy configuration."

**Comment by bohnertchris** [comment]
To be honest, the original text was clear to me. However, we have created an internal ticket and the cloud service author will review.

**Comment by vishabhguptaadobe** [comment]
ok, i will update this on CQDOC-15797

**Comment by vishabhguptaadobe** [comment]
Created a clone of this task as the original was closed:
CQDOC-15822

**Comment by vishabhguptaadobe** [comment]
@actinium15 
Does the following message is clear?

"You must have only one IMS configuration that passes the health check. Do not create multiple IMS configurations.
If the configuration does not pass the health check, it is invalid. You must delete it and create a new valid configuration."

**Comment by actinium15** [comment]
>You must have only one IMS configuration that passes the health check. Do not create multiple IMS configurations.
If the configuration does not pass the health check, it is invalid. You must delete it and create a new, valid configuration.

hi @vishabhguptaadobe, I feel conflating cardinality and validity of a config in the same sentence muddies the message we want to get across. When the 1st sentence of the alternative you proposed is read _in isolation_, IMHO, it seems to suggest that it is OK to have multiple configs as long as only one of them passes the health-check.
The 2nd sentence attempts to clarify that multiple configs themselves shouldn't be created, but at best is read as contradictory and at worst appears too late for cognition to kick in (skipping over the complete sentences in the documentation while in hurry is too common in my experience)...

To be clear, the message is we want to get across is:
1. at any point in time, there should only be one IMS configuration for BP in the system
  * it doesn't matter whether it is valid/health-checked or not. Creating multiple configurations, even if only one of them is valid/health-checked, is a situation we'd like to avoid.
2. If BP integration is expected to work correctly, then the singleton BP IMS config _has to be_ valid.

That's the reason why I suggested my [preference in the issue description](https://github.com/AdobeDocs/experience-manager-cloud-service.en/issues/21#issue-598960633) for:
>Create only a single IMS configuration. Do not create multiple IMS configurations.
Make sure that the configuration is healthy. In case, the configuration is unhealthy, delete it and create a new, healthy configuration.

However, I see that the text you sought feedback on is live already - and if you'd like to keep that verbiage, maybe it can be tweaked to:
>You must have only one IMS configuration. Do not create multiple IMS configurations.
Ensure that the IMS configuration passes the health check. If the configuration does not pass the health check, it is invalid. You must delete it and create a new, valid configuration.

\cc: @ashishguptaiitb

**Comment by vishabhguptaadobe** [comment]
@actinium15 ,
Thanks for sharing the views, going ahead with this:

"You must have only one IMS configuration. Do not create multiple IMS configurations.
Ensure that the IMS configuration passes the health check. If the configuration does not pass the health check, it is invalid. You must delete it and create a new, valid configuration."

**Comment by vishabhguptaadobe** [comment]
Fixed in the following articles:
https://docs.adobe.com/content/help/en/experience-manager-65/assets/brandportal/configure-aem-assets-with-brand-portal.html
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/brand-portal/configure-aem-assets-with-brand-portal.html
https://docs.adobe.com/content/help/en/experience-manager-64/assets/brandportal/configure-aem-assets-with-brand-portal.html
https://helpx.adobe.com/experience-manager/6-3/assets/using/brand-portal-configuring-integration.html

**Comment by bohnertchris** [comment]
Test comment
