### ISSUE TITLE
Documentation - Anchor heading issue 

### ISSUE THREAD

**Issue by BrijeshRnDSpace** [AdobeDocs/experience-manager-cloud-service.en#211]
Issue in ./help/implementing/cloud-manager/navigation.md

HTML coding appear in documentation. Almost for all the pages. See example:
https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/navigation

![image](https://github.com/user-attachments/assets/e163dc04-0c9a-4a74-b4f6-787080768420)

**Comment by guillaumecarlino** [comment]
@BrijeshRnDSpace, thanks for reporting. The platform team is aware and they are working on it.

**Comment by guillaumecarlino** [comment]
Hopefully it'll be fixed soon.
