### ISSUE TITLE
Visible Anchor Tags in Documentation

### ISSUE THREAD

**Issue by danadascalescu00** [AdobeDocs/experience-manager-cloud-service.en#212]
Issue in ./help/implementing/deploying/aem-version-updates.md

### Description
Certain sections of the public documentation contain visible anchor tags, such as `:headding-anchor:ci-cd`. These seem to be placeholders that weren’t removed and affect the readability of the docs.

### Actual Behaviour
Anchor tags are visible, which creates unnecessary noise in the documentation.

<img width="1002" alt="Screenshot 2024-10-04 at 16 33 45" src="https://github.com/user-attachments/assets/f551a0fe-c157-4cff-970d-7a78e471f230">

**Comment by guillaumecarlino** [comment]
That has been fixed by the platform team. Thanks.
