### ISSUE TITLE
Deleting and Unpublishing

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#213]
Issue in ./help/sites-cloud/authoring/getting-started/quick-start.md
It is not clear in this doc if deleting your content will result in the automatic unpublication of that content or if further steps are necessary.

**Comment by aheim0** [comment]
Thanks for raising this - we will review.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
As this is a "Quick Start" Guide the information is designed to be kept to a minimum. However, we have added some links to the detailed content for when further information is required.
Closing issue.
