### ISSUE TITLE
There is no document explaining how to use the "Clone" button

### ISSUE THREAD

**Issue by Lexie1919** [AdobeDocs/experience-manager-cloud-service.en#213]
Issue in ./help/sites-cloud/authoring/launches/creating.md

For AEM Cloud Service -> Launches, there is no document explaining how to use the "Clone" button, when customer clone an existing launch whether they are presented with the option to rename the launch etc. Could you please add that? For reference this is the feature I am talking about https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/sites/authoring/launches/creating

**Comment by raimanS** [comment]
Thank you for opening this issue. We will look into it.

**Comment by raimanS** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Thanks for raising this. Updates have been made and will be published soon.
Closing issue now.
