### ISSUE TITLE
Mod Macro missing from the list of supported modules

### ISSUE THREAD

**Issue by dcreaadobe** [AdobeDocs/experience-manager-cloud-service.en#218]
Hi Team,
as per the following SKYOPS-32961 
apache mod macro should be already available starting 2022.6.0 version, but documentation is not updated yet.
Can you please verify?
thank you

Issue in ./help/implementing/dispatcher/disp-overview.md

**Comment by raimanS** [comment]
Thank you for opening the issue. We have planned a documentation update for mod_macro. I will post here once it is available.

**Comment by raimanS** [comment]
mod_macro has been added to the list of supported apache modules. See [1].

[1] - https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/disp-overview.html
