### ISSUE TITLE
[Redacted]

### ISSUE THREAD

**Issue by mattlaun** [AdobeDocs/experience-manager-cloud-service.en#22]
Issue in ./help/operations/backup.md

[Redacted]

See CQDOC-19731 for details.

**Comment by anujkapo** [comment]
Thanks @mattlaun. We will fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was addressed in commits 5b69305 and 9ac2380.
