### ISSUE TITLE
Link doesn

### ISSUE THREAD

**Issue by ptager** [AdobeDocs/experience-manager-cloud-service.en#22]
Issue in help/landing/home.md at the following location:

- https://docs.adobe.com/content/help/en/experience-manager-cloud-service/release-notes/home.html

**Comment by ptager** [comment]
The link for the Current Release Notes should point to this URL:
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/release-notes/release-notes/release-notes-current.html

in the section below:
Key Release Information
**Current Release Notes**
What is New
Notable Changes
Known Issues
Deprecated and Removed Features

**Comment by ashishguptaiitb** [comment]
It is fixed @ptager . Thanks for sharing.

**Comment by bohnertchris** [comment]
CQDOC-15829
