### ISSUE TITLE
API Key vs. Client ID. 

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#220]
Issue in ./help/sites-cloud/integrating/integration-adobe-target-ims.md
In the section "Completing IMS configuration in AEM" you refer to getting the API key from the overview section. When I go to the overview section, there is no "API Key" there. But there is a "Client ID". If they are the same -and I'm not sure if they are, it should be referred to consistently to avoid confusion and ambiguity.

**Comment by anujkapo** [comment]
Thanks, @alisonasanchez. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
After configuring an API, the Project overview should include a **Credentials** section. This will have a box for **API Key**, showing the **API KEY (CLIENT ID)**. The value can be copied to the clipboard using the **Copy** button.

This has been re-confirmed with a test.

Closing issue now.
