### ISSUE TITLE
Grammar/content clarity

### ISSUE THREAD

**Issue by jkerger** [AdobeDocs/experience-manager-cloud-service.en#23]
Issue in help/assets/use-assets-across-connected-assets-instances.md

The sentence in the second section has grammar issues.  I'm not sure what the sentence is trying to convey:
To do an AEM administrator do a one-time integration of a local deployment of AEM Sites with a different (remote) deployment of AEM Assets.

The sentence could have possibly meant to say:
This feature allows an AEM administrator to do a one-time integration of a local deployment of AEM Sites with a different (remote) deployment of AEM Assets.

**Comment by ashishguptaiitb** [comment]
Indeed a typo @jkerger . I shall update it. Thanks.

**Comment by ashishguptaiitb** [comment]
It is updated at https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/admin/use-assets-across-connected-assets-instances.html
Thanks @jkerger 
If there's any more feedback, please do share.
