### ISSUE TITLE
2022.7.0 Release Date For Cloud Manager

### ISSUE THREAD

**Issue by sharchen107** [AdobeDocs/experience-manager-cloud-service.en#233]
Issue in ./help/implementing/cloud-manager/release-notes-cloud-manager/release-notes-cm-current.md

Hi, is the release date for Cloud Manager 2022.7.0 30 June 2022? Why is it a different date from the date listed here: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/release-notes/release-notes-current.html#release-date? -- The next release (2022.7.0) is planned for August 8, 2022.

**Comment by aheim0** [comment]
Thanks for raising this - we will fix it.

The release date is indeed August 8, 2022. It was postponed to maintain quality standards.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sharchen107** [comment]
Ok thank you!

Do Cloud Manager updates usually have a different release date than Sites/Assets?

Sharon Chen |  Sr Technical Account Manager  |  Adobe | C +64 (0)27 647 2463 |  ***@***.******@***.***>
________________________________

**Comment by aheim0** [comment]
"Do Cloud Manager updates usually have a different release date than Sites/Assets?"

Yes, the standalone Cloud Manager has a different release cycle/date from the Cloud Manager included in AEM as a Cloud Service (inc. Sites and Assets).

**Comment by aheim0** [comment]
The date has been adjusted - see https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/cloud-manager/release-notes-cm-current.html?lang=en#release-date

Thanks for highlighting this.

Closing issue now.
