### ISSUE TITLE
Warnings about back buttons

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#25]
Issue in ./help/security/ims-support.md
There should be a note added somewhere that warns that using the back button after signing in, they might be asked to sign in again even if they have selected to stay logged in and may get an access denied error as well.

**Comment by aheim0** [comment]
Thank you for raising this, but that is standard browser behavior. We do not document at that level, especially as the Security documentation is for experienced users.
Closing this issue.
