### ISSUE TITLE
The "Accessing Developer Console" section of this page should specify what permissions are needed in Admin Console

### ISSUE THREAD

**Issue by kaushalmall** [AdobeDocs/experience-manager-cloud-service.en#26]
Issue in help/implementing/cloud-manager/manage-environments.md

**Comment by jyotikas** [comment]
@kaushalmall , thank you submitting the requirement. I will consult the PMs to add the requisite information.

**Comment by bohnertchris** [comment]
CQDOC-16121

**Comment by jyotikas** [comment]
@kaushalmall, the page is now updated with more information:
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/using-cloud-manager/manage-environments.html#accessing-developer-console
