### ISSUE TITLE
Link additional documentation

### ISSUE THREAD

**Issue by bartoszWesolowski** [AdobeDocs/experience-manager-cloud-service.en#28]
Issue in ./help/implementing/cloud-manager/environment-variables.md

Env variables can be used in OSGI config - it would be worth to connect this article with the one that explains how to configure OSGI services using env variables - maybe separate section with a link to the dedicated page would be enough.

Thanks,
Bartek

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @bartoszWesolowski. That is in line with issue #29 and we will investigate.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This request is closely related to issue #29 and was likewise closed with the improvements made for that issue.
