### ISSUE TITLE
Link to download the CTT is missing on this page

### ISSUE THREAD

**Issue by kaushalmall** [AdobeDocs/experience-manager-cloud-service.en#28]
Issue in help/move-to-cloud-service/content-transfer-tool/using-content-transfer-tool.md

**Comment by kaushalmall** [comment]
@jyotikas FYI

**Comment by jyotikas** [comment]
Thank you @kaushalmall for reporting.
The link is now available:
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/moving/cloud-migration/content-transfer-tool/using-content-transfer-tool.html#availability
