### ISSUE TITLE
How to retrieve access token

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#29]
Issue in help/move-to-cloud-service/content-transfer-tool/using-content-transfer-tool.md

_"You can retrieve the access token from the author instance by navigating to /libs/granite/migration/token.json ."_

It would be helpful to mention on what instance to get the access token (the source, I believe?)

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @ackoch. We will have a look.

CQDOC-16193

**Comment by jyotikas** [comment]
@ackoch thank you reporting. The caveat is now updated. Please feel free to re-open the issue if it is still unclear. Here's the link to the updated page:

https://docs.adobe.com/content/help/en/experience-manager-cloud-service/moving/cloud-migration/content-transfer-tool/using-content-transfer-tool.html#running-tool
