### ISSUE TITLE
Where can environment variables be used

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#29]
Issue in ./help/implementing/cloud-manager/environment-variables.md
Would be nice to have some clarification on where environment variables can be used and where they cannot. For example, can you use environment variables in dispatcher configurations?

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @alisonasanchez. We will investigate.

**Comment by bohnertchris** [comment]
This content has been improved via commit 4c097f7 in this repository and commit d8a7e0c in the AMS Cloud Manager repository.
