### ISSUE TITLE
Provide a breadcrumb navigation

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#3]
If someone is on e.g. https://docs.adobe.com/content/help/en/experience-manager-cloud-service/operations/replication.html there is no navigation link which allows to navigate to other sections (like https://docs.adobe.com/content/help/en/experience-manager-cloud-service/core-concepts/architecture.html#) pages or back to the landing page (at https://docs.adobe.com/content/help/en/experience-manager-cloud-service/landing/home.html) directly.

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @kwin. We overlooked updating some metadata and now the banner links point to the correct locations (see commit 94a3151). This means:

- From any article, you can easily return to the user guide overview of that article.
- From any article, you can easily return to the overview of all user guides of AEM as a Cloud Service.

We arrange our topics into user guides, which group similar topics like authoring, operations, integrating, etc. It was a conscious decision to separate them this way and only show the content of the current user guide in the left navigation panel so it would not be overwhelming for the user to navigate by including topics from other user guides.
![screen-shot 2020-01-22 at 11 24 41](https://user-images.githubusercontent.com/38424477/72887003-18e7cb00-3d0b-11ea-888a-76082019c517.png)

**Comment by kwin** [comment]
Perfect, thanks for the quick fix!
