### ISSUE TITLE
Not enough information

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#30]
Issue in ./help/onboarding/aem-cs-team-product-profiles.md

There is talk in this about Cloud Manager Product Profiles, but not how to actually assign them. Specific steps and screenshots would be nice. For example, how to add the Developer profile. The one screenshot on this page doesn't show any of that.

**Comment by TylerRush** [comment]
@adobe export issue to Jira project CQDOC

**Comment by TylerRush** [comment]
Thank you for the suggestion, @alisonasanchez. We will investigate.

**Comment by bohnertchris** [comment]
We have linked this page to the pages detailing adding AEM and CM product profiles in commit 6eda072.
