### ISSUE TITLE
Edit this page link results in 404 on Securing the Author Tier page

### ISSUE THREAD

**Issue by deltaworld** [AdobeDocs/experience-manager-cloud-service.en#32]
Issue in help/implementing/author-tier/securing-the-author-tier.md

On the page https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/author-tier/securing-the-author-tier.html

the link "Edit this page"  directs the user to "https://github.com/AdobeDocs/experience-manager-cloud-service.en/tree/master/help/implementing/author-tier/securing-the-author-tier.md" and results in a 404.

**Comment by bohnertchris** [comment]
Thank you for reporting, @deltaworld. We will get this fixed.

CQDOC-16332

**Comment by aheim0** [comment]
@deltaworld 

I have checked the link several times (yesterday and today) and everything is working as expected - no 404.
Looking at the last published date of the page, against the date of this issue it seems that content has been published in the meantime.

Can we ask you to confirm that everything is now working for you as well? Thanks.

**Comment by aheim0** [comment]
@deltaworld 
I have had confirmation that this was due to an issue with mirroring, which was fixed very shortly after you raised this issue.
I will close this issue now. Please contact us again if you have further problems.
