### ISSUE TITLE
Incorrect path in "Enable Styles Tab in Edit Dialog" section

### ISSUE THREAD

**Issue by madoni** [AdobeDocs/experience-manager-cloud-service.en#36]
Issue in help/sites-cloud/authoring/features/style-system.md

This path does not exist:
`path = "/mnt/overlay/cq/gui/components/authoring/dialog/style/tab_edit/styletab"`

**Comment by aheim0** [comment]
Thank you for raising this @madoni, we will investigate.

**Comment by aheim0** [comment]
@madoni 
The paths you refer to are part of the Setup section that detail "how-to" enable Styles. For this reason they are not defined ootb.

To provide more context and background information I have updated the page with a note and links to related information.

Hope that helps. Will close this issue, but let us know if you need more information.
