### ISSUE TITLE
[AEM CS] Review guidance around Use Groups as members of Product Profiles

### ISSUE THREAD

**Issue by davidjgonzalez** [AdobeDocs/experience-manager-cloud-service.en#36]
Issue in ./help/security/ims-support.md

I believe the Note stating user groups cannot be added to product profiles is outdated now. Can you confirm, and adjust the doc accordingly?

![2022-11-16 at 12 11 PM](https://user-images.githubusercontent.com/1451868/202247734-66c663d4-1631-4c1f-a1e5-ac5db7b85c04.png)

This originally spawned form https://github.com/AdobeDocs/experience-manager-learn.en/issues/97, however the Learn content appears to be correct.

Thanks!

**Comment by TylerRush** [comment]
Thanks for your feedback @davidjgonzalez. We are investigating this issue.

**Comment by TylerRush** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarchiz** [comment]
Hi, that note is still valid. Eng is still working to enable that type of nesting. Closing this as a consequence.
