### ISSUE TITLE
Add more details about the tool in 6.2

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-cloud-service.en#37]
Issue in help/move-to-cloud-service/cloud-readiness-analyzer/using-cloud-readiness-analyzer.md

For AEM 6.2, Maybe its better to add a screenshot to show the UI:

![Picture1](https://user-images.githubusercontent.com/54867395/87064069-35a28d00-c1dd-11ea-9226-797d0e349ede.png)

It shows Unsupported AEM version but users can still download csv.

**Comment by jyotikas** [comment]
The docs are now updated. CRA is now re-branded as Best Practices Analyzer. Please feel free to re-open the issue if there are any further updates required.
