### ISSUE TITLE
Wrong dynamic media path on AEMCS

### ISSUE THREAD

**Issue by Yogiraj24** [AdobeDocs/experience-manager-cloud-service.en#38]
Issue in ./help/assets/dynamic-media/linking-urls-to-yourwebapplication.md

The path provided to get video rendition here "Obtain a video URL for a published video rendition" is wrong for AEM Cloud

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
The path is for explanation purposes only; it is not the actual path you copy.
Closing.
