### ISSUE TITLE
Explicitly mention what pre-release channel includes and doesn't include

### ISSUE THREAD

**Issue by nishtalle** [AdobeDocs/experience-manager-cloud-service.en#41]
Add a note to explicitly mention what the pre-release channel includes and doesn't include. I heard today (12/19/22) on AEM Brown Bag session that pre-release channel does not necessarily include the actual build which will be released and shouldn't be relied on to test all features in the upcoming build. Prerelease channel is a way to test prerelease features which have been mentioned on the release notes and labeled as prerelease.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/prerelease.html?lang=en

**Comment by bohnertchris** [comment]
Hello, @nishtalle, and thank you for your comment. I am not clear what exactly you are asking. We already mention that the prerelease does not include all features.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/prerelease.html#considerations

Do you feel that this should be worded differently?

**Comment by nishtalle** [comment]
Hello Chris, 
I think we should mention what does not get included in the prerelease channel. Article mentions... "The prerelease channel allows you to preview features scheduled for the upcoming monthly release..." but does not explicitly mention what isn't included. Hence this is taken to mean it's inclusive of the actual release/build going to be released following month. This got clarified on an internal call. Sending you some screenshots and additional context over email shortly.

**Comment by bohnertchris** [comment]
As discussed via email, the required information is already covered in the **Considerations** section of the existing document.

> The prerelease channel does not necessarily contain all new features to be rolled out in the following release.

Closing this issue.
