### ISSUE TITLE
Include CRA note

### ISSUE THREAD

**Issue by alpinecruzar** [AdobeDocs/experience-manager-cloud-service.en#41]
Issue in help/move-to-cloud-service/planning.md
Might be worth mentioning CRA tool as a part of the planning doc now that it is available.

**Comment by anujkapo** [comment]
Thanks for the suggestion, @alpinecruzar. We will fix it.

**Comment by anujkapo** [comment]
Tacked with CQDOC-16686.

**Comment by jyotikas** [comment]
Thank you @alpinecruzar  for the suggestion. The Page now shows the required mention of CRA tool.
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/moving/phases/planning.html#access-cloud-readiness
