### ISSUE TITLE
Table data is unreadable

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-cloud-service.en#44]
Even at 1400px wide, the table data is unreadable and provides a poor visitor experience.

![screencapture](https://user-images.githubusercontent.com/6520270/92258106-f1a9cc80-ee9b-11ea-918f-ee2adea3896f.png)

**Comment by raimanS** [comment]
Hi. Thanks for pointing this issue. We will try to update the tables so the content appears more clearly.

**Comment by aheim0** [comment]
Tracked with CQDOC-16759.

**Comment by raimanS** [comment]
Updated the table to make it more readable.
