### ISSUE TITLE
Metadata description for page showing "To be completed"

### ISSUE THREAD

**Issue by deltaworld** [AdobeDocs/experience-manager-cloud-service.en#46]
When viewing the source code and when embedding the link in other social media posts the description is displayed and is showing the placeholder message of "To be completed"

> docs.adobe.com
> The AEM as a Cloud Service SDK
> To be completed

L58: view-source:https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/aem-as-a-cloud-service-sdk.html#refreshing-a-local-project-with-a-new-skd-version

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-16786.

**Comment by aheim0** [comment]
A description has been added to this page (and also the Development Guidelines). The pages have been republished.
Closing this issue now.
