### ISSUE TITLE
do we have PDF versions of these web pages?

### ISSUE THREAD

**Issue by dhicken** [AdobeDocs/experience-manager-cloud-service.en#47]
Issue in ./help/overview/home.md

**Comment by bohnertchris** [comment]
Thanks for the question, @dhicken. We work hard to make sure that our documentation is up-to-date. Therefore all user documentation for AEM as a Cloud Service is provided as freely-accessible HTML content via the Experience League website. The Experience League team has made sure that the content renders properly regardless of device or browser.

**Comment by dhicken** [comment]
Having PDF in addition to html would make it much easier to search.

[Internal email chain redacted]

**Comment by bohnertchris** [comment]
Search is of course very important to our docs, but I do not see how converting all of the documentation to PDF would improve that experience. Experience League has a comprehensive search system built into the platform. That team is open to any suggestions you might have for improving search should you find it wanting. Also note that all documentation is based on GitHub and you can use this platform and its powerful search as well. Finally you are welcome to clone any repository locally if search performance is key and use Unix standard tools like grep on your own machine.
