### ISSUE TITLE
Reference new Experience League material

### ISSUE THREAD

**Issue by gillesmetz** [AdobeDocs/experience-manager-cloud-service.en#48]
Issue in help/security/ims-support.md

A new training has been recently released on Experience League on how to configure access to AEM for Administrators : https://experienceleague.adobe.com/?recommended=ExperienceManager-A-1-2020.1.aem

It'd be great to reference it on the page https://docs.adobe.com/content/help/en/experience-manager-cloud-service/security/ims-support.html

**Comment by TylerRush** [comment]
CQDOC-16854 for reference.

**Comment by bohnertchris** [comment]
Thanks for the suggestion, @gillesmetz. We linked to this content in commit 5ec85e2.
