### ISSUE TITLE
By default the front-end pipeline uses Node 14, but 16 and 16 are also available.

### ISSUE THREAD

**Issue by Rampai94** [AdobeDocs/experience-manager-cloud-service.en#48]
Issue in ./help/implementing/developing/introduction/developing-with-front-end-pipelines.md

Section:
Node Versions
By default the front-end pipeline uses Node 14, but 16 and 16 are also available.

Text mentions 16 and 16 and this looks like a typo.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @Rampai94. We will fix it.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected in merge 6bc0d47.
