### ISSUE TITLE
Connected Assets - Source and Target

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#51]
Issue in help/assets/use-assets-across-connected-assets-instances.md

From the table on this picture it is not 100% clear what combination CS / on-prem works.. I assume the systems in the left column  are the source systems (from...) and the top row denote the target system (to...).

But it would help if that is denoted explicitly..

**Comment by ashishguptaiitb** [comment]
Hi @ackoch , the features works with Sites deployment pulling in assets from Assets deployment. From the perspective of original assets, the Assets deployment is source (provider of the asset). From the perspective of usage of the asset, the Sites deployment is the source (origin of fetch request). I'm not sure how to define what's to and from?

**Comment by ackoch** [comment]
The question is - and I thought this is what the table is about - if we can pull Assets from On-premise to Cloud Service and from  Cloud Service to On-premise.

**Comment by aheim0** [comment]
Tracked with CQDOC-17001.

**Comment by ashishguptaiitb** [comment]
Hi @ackoch , as advised by PM, I've mentioned that Sites deployment is the target and Assets deployment is the source. Also, on-prem Assets is not supported which is called out in the last row of the table. 
see https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/admin/use-assets-across-connected-assets-instances.html#admin 

I'm closing this issue. Do let us know if anything is required.
