### ISSUE TITLE
Needed to set Video Profile on target asset folder 

### ISSUE THREAD

**Issue by kono-paku** [AdobeDocs/experience-manager-cloud-service.en#52]
Issue in help/assets/dynamic-media/config-dm.md

Hello. I have tried Dynamic Media as Cloud Service.
If it is not to set Video Profile as 「Adaptive Video Encoding」on target asset folder like below, it is not working.

Could you review the document?

<img width="876" alt="Screen Shot 2020-10-28 at 9 53 48" src="https://user-images.githubusercontent.com/38544174/97377693-f58a2600-1903-11eb-8edb-eceea79f4a79.png">

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17020.

**Comment by rickbrough** [comment]
Sorry. It is not clear to me what question you are asking. If you are trying to apply a video profile to a folder, please see [Applying a Video Profile to folders](https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/dynamicmedia/video-profiles.html#applying-a-video-profile-to-folders)

**Comment by kono-paku** [comment]
@rickbrough 

Is this in the page for Dynamic Media configuration for AEM CS?

https://docs.adobe.com/content/help/en/experience-manager-cloud-service/assets/dynamicmedia/video-profiles.html#applying-a-video-profile-to-folders

Above one should be in the help/assets/dynamic-media/config-dm.md

I have barely used Dynamic Media on AEM CA after configuring the folder with video profile.

Without configuring the folder,
Dynamic Media component does not work.
