### ISSUE TITLE
Typo in the image

### ISSUE THREAD

**Issue by OpekunAleksei** [AdobeDocs/experience-manager-cloud-service.en#52]
Issue in ./help/implementing/developing/introduction/configurations.md

![image](https://user-images.githubusercontent.com/31468362/215324505-70ba0de6-4eb6-489a-b664-ceb607fd7fbf.png)

The node name should be wknd not wkns

**Comment by anujkapo** [comment]
Thanks for reporting, @OpekunAleksei. We have fixed the typo. 
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/developing/configurations.html
