### ISSUE TITLE
GraphQL Sorting, Pagination and IN operator not supported

### ISSUE THREAD

**Issue by mkovacek** [AdobeDocs/experience-manager-cloud-service.en#53]
Hi all,
The documentation says that Sorting and Pagination is available, but the truth is that it is not possible to use those.  

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/headless/graphql-api/sample-queries.html?lang=en

https://github.com/AdobeDocs/experience-manager-cloud-service.en/blob/main/help/headless/graphql-api/content-fragments.md

Is there some configuration in AEM that will enable those features?

Also part of graphql specification https://spec.graphql.org/October2021/  there are more features, and operators available but in AEM are not supported. For example, IntOperator "IN" 

What is the reason and when they will be available?

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
The Paging and Sorting functionality is available as Prerelease. You can apply for access.

This information is (or should be) registered in the Release Notes. As these are managed by another group I will pass your request on, and ask them to investigate.

The same group are responsible for new features, and the related roadmap. We (documentation) are not always informed of every decision, and also, as I am sure you will understand, we cannot discuss any such details that we do have on a public platform. 

Thank you for your understanding.

Closing this ticket now.

**Comment by mkovacek** [comment]
Is there another repository where I can address it?

**Comment by aheim0** [comment]
Not that I am aware of. Internally we will track everything with the CQDOC issue. Otherwise I would suggest that you contact either Sales or Support depending on the questions you have.
