### ISSUE TITLE
Native Java 11 support not yet reflected in documentation

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#53]
Issue in help/onboarding/getting-access-to-aem-in-cloud/build-environment-details.md

According to https://docs.adobe.com/content/help/en/experience-manager-cloud-service/release-notes/release-notes/release-notes-current.html

> The Cloud Manager build container now supports both Java 8 and Java 11.

But still it is mentioned in help/onboarding/getting-access-to-aem-in-cloud/build-environment-details.md that I have to configure Java 11 compilation via toolchains and also

> The Cloud Manager project build is still using Java 8 to invoke Maven, therefore checking or enforcing the Java version configured in the toolchain plugin through plugins like the Apache Maven Enforcer Plugin does not work and such plugins must not be used.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17025.

**Comment by jyotikas** [comment]
Thank you @kwin for reporting.
The language in the Release Notes is now updates:
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/release-notes/release-notes/release-notes-current.html#cloud-manager
