### ISSUE TITLE
Right hand table of content is missing

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#54]
Issue in ./help/implementing/cloud-manager/getting-access-to-aem-in-cloud/editing-programs.md

table of contents on right hand side is missing on this page. Wanted a direct link to deleting a sandbox.

**Comment by anujkapo** [comment]
Thanks, @alisonasanchez. We will investigate.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was fixed with merge 0181ed8.
