### ISSUE TITLE
Documentation still pointing to AEM 6.5 Javadoc

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#55]
There are a lot of links in the AEMaaCS site still pointing to the AEM 6.5 Javadoc: 
https://helpx.adobe.com/experience-manager/6-5/sites/developing/using/reference-materials/javadoc/

Instead those should point to https://docs.adobe.com/content/help/en/experience-manager-cloud-service-javadoc/

You can find those places via https://github.com/AdobeDocs/experience-manager-cloud-service.en/search?p=1&q=reference-materials

**Comment by anujkapo** [comment]
Thanks, @kwin for pointing this out. We will fix it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17086.
