### ISSUE TITLE
Bad pom.xml structure

### ISSUE THREAD

**Issue by demo2b** [AdobeDocs/experience-manager-cloud-service.en#57]
Issue in ./help/onboarding/getting-access-to-aem-in-cloud/setting-up-project.md

In the code snippet above the text "And finally reference the server id inside the pom.xml file..."
The XML structure is not correct, the <repositories> tag is not allowed has child of <build>, it should be directly under the <profile> one.

**Comment by anujkapo** [comment]
Thanks, @demo2b for reporting the issue. We will take a look.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17093.

**Comment by justinedelson** [comment]
@demo2b do you mean "below the text"? because the settings.xml piece is correct in that it has a hierarchy of `<settings>` then `<servers>` then `<server>`.

**Comment by demo2b** [comment]
Sorry for the delay, yes sorry, I meant 'bellow' yes.
Don't know why few words of my comment just disapeared, maybe because they was "<tag>"...
Anyway, I think you got it right ?
Thanks & sorry.

**Comment by justinedelson** [comment]
thanks for clarifying @demo2b

**Comment by justinedelson** [comment]
I think this issue can be closed. https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/using-cloud-manager/create-application-project/setting-up-project.html?lang=en has the right pom structure now.

**Comment by aheim0** [comment]
Thanks for the follow-up and confirmation. 
Closing this issue.
