### ISSUE TITLE
All Links on the page take users to experienceleague.adobe.com homepage

### ISSUE THREAD

**Issue by jbrarAdobe** [AdobeDocs/experience-manager-cloud-service.en#59]
Issue in ./help/onboarding/getting-access-to-aem-in-cloud/sandbox-programs.md

All links on the page take users to experienceleague.adobe.com homepage

**Comment by jyotikas** [comment]
Thank you @jbrarAdobe for reporting. The issue is now fixed:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/onboarding/getting-access/cloud-service-programs/sandbox-programs.html?lang=en#sandbox-programs

**Comment by aheim0** [comment]
Tracked with CQDOC-17133.
