### ISSUE TITLE
Contradicting statement on the document

### ISSUE THREAD

**Issue by s-aryal** [AdobeDocs/experience-manager-cloud-service.en#59]
Issue in ./help/security/ims-support.md

Introduction third bullet suggest Users and Groups can be assigned to product profiles associated with AEM as a Cloud Service instances, allowing them to log in to that instance. But the Note in the second block has contradicting statement AEM currently does not support assigning groups to profiles. Users should be added individually instead.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarchiz** [comment]
Hi @s-aryal,

Thanks for reporting this.

We've made changes to the documentation to make it clearer that groups cannot be assigned to product profiles.
