### ISSUE TITLE
Clarify handling of OSGi bundles, OSGi configuration and nested packages inside content packages

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#60]
Issue in ./help/implementing/developing/introduction/rapid-development-environments.md

Although it is explicitly mentioned that Dispatcher Configuration needs to be deployed separately it is not clear whether the RDE can deal with container content-packages (containing other content packages, OSGi bundles and OSGi configuration).
Is the OSGi installer (https://sling.apache.org/documentation/bundles/osgi-installer.html) part of the RDE server?

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarchiz** [comment]
Hi @kwin - we've made some adjustments to the docs based on your questions. Please have a look. Thanks.

**Comment by kwin** [comment]
Thanks a lot. Much better now.
