### ISSUE TITLE
Download limit link under "Best practices and troubleshooting" section doesn't take the users anywhere

### ISSUE THREAD

**Issue by sarathraju** [AdobeDocs/experience-manager-cloud-service.en#61]
Issue in ./help/assets/share-assets.md

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by guillaumecarlino** [comment]
Thanks for reporting, I removed the link and added the default limit.
