### ISSUE TITLE
Responsive layout GH repo contains broken links

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [AdobeDocs/experience-manager-cloud-service.en#64]
Hello,

The page that covers responsive layout specifically mentions a GH repo with some examples for the FE devs [here](https://github.com/AdobeDocs/experience-manager-cloud-service.en/blob/master/help/sites-cloud/authoring/features/responsive-layout.md):

>[!TIP]
>
>Adobe provides [GitHub documentation](https://adobe-marketing-cloud.github.io/aem-responsivegrid/) of the responsive layout as a reference that can be given to the front-end developers allowing them to use the AEM grid outside of AEM, for example when creating static HTML mock-ups for a future AEM site.

This GH page itself does contain relevant content, however, the link to the docs on that page is broken - I wonder if somebody can fix it?

Thanks.

**Comment by anujkapo** [comment]
Thanks, @dzmitry-kankalovich. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-17195.

**Comment by bohnertchris** [comment]
Thanks for pointing this out, @dzmitry-kankalovich. Looks like the redirect was broken during the migration of our documentation to the Experience League platform. This has been corrected.
