### ISSUE TITLE
Terminology issue <Sample DocBugBlitz test>

### ISSUE THREAD

**Issue by BharathValse** [AdobeDocs/experience-manager-cloud-service.en#66]
Issue in ./help/overview/terminology.md

This is a test issue created with Tyler to test the workflow.

Label: DocBugBlitz2023

**Comment by TylerRush** [comment]
Thanks for the feedback. We will investigate this issue and update the documentation accordingly.

<This is a test of the workflow for Docbugblitz2023>

**Comment by TylerRush** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Closing this issue now.
