### ISSUE TITLE
Tools > Operations is not available in the cloud

### ISSUE THREAD

**Issue by swaroop61** [AdobeDocs/experience-manager-cloud-service.en#69]
Issue in ./en/help/operations/asynchronous-jobs.md

Issue Description:
For Aem in cloud, the Operations option is not visible

example: these instructions on this page do not work in cloud.

Global Navigation -> Tools -> Operations -> Jobs
Tools > Operations > Web Console

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
This is a duplicate of #71
