### ISSUE TITLE
AEM dispatcher tools not reloading on changing files

### ISSUE THREAD

**Issue by julioramirez96** [AdobeDocs/experience-manager-cloud-service.en#7]
Hello, Iḿ trying to use the hot reload feature of dispatcher tools on docker.
But seems not working
![image](https://user-images.githubusercontent.com/74867861/187094471-0fad391a-fa52-407f-9819-1c30d198cb27.png)

The deamon is lauched but after change any file of my dispatcher project the changes are not reflected, also any log in the console appear

**Comment by aheim0** [comment]
This seems to be a question for Support, whereas these issues are only intended for questions/suggestions about documentation.

We suggest that you contact your support representative. Closing this issue.
