### ISSUE TITLE
Create asset programmatically

### ISSUE THREAD

**Issue by kele23** [AdobeDocs/experience-manager-cloud-service.en#70]
Issue in ./help/assets/developer-reference-material-apis.md

I cannot understand how to create an Asset programmatically in AEM Cloud service.

For a new project I have to download assets from a remote server and add it to the AEM DAM programmatically. 
I need something, like in the previous AEM versions, that enables me to get create an Asset from an InputStream. I didn't want to make an external system that trigger the upload using HTTP API.

Can you help me?

**Comment by aheim0** [comment]
Thank you for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17330.

**Comment by ashishguptaiitb** [comment]
Hi @kele23 may I request you to check out https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/admin/developer-reference-material-apis.html#asset-upload-technical 
and https://github.com/adobe/aem-upload
and suggest what can be improved in the docs?

**Comment by kele23** [comment]
Hi @ashishguptaiitb,
I've read the docs,
about aem-upload library I think is well documented but the problem is that it is a JS/NodeJS library and I cannot use it on my custom OSGI component. I have to create the client and launch it externally from AEM.
But as documentation says it is the only way to create a new asset binary. 
![image](https://user-images.githubusercontent.com/3380263/105011175-e915f500-5a3c-11eb-82eb-cfba000200ec.png)


My problem is that if I want to handle my assets in this way (image) I cannot understand how to do it.
![image](https://user-images.githubusercontent.com/3380263/105006458-fe882080-5a36-11eb-9e47-fe660b06db36.png)

In the documentation I see that I can upload an asset only using a client and making HTTP requests, but sometimes I need to create assets directly in AEM or, as in my case, import some images from other servers. 
How can I do this? Is there an an OSGI service that I can use?

**Comment by ashishguptaiitb** [comment]
Hi @kele23 , AEM as a Cloud Service supports programmatic upload of assets using the aem-upload method mentioned in the help article. See https://github.com/adobe/aem-upload#background for more details. The import you mentioned is not possible.
