### ISSUE TITLE
Purge Completed Jobs

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#71]
Issue in ./help/operations/asynchronous-jobs.md

In the Purge Completed Jobs section, it says to go to Tools > Operations, which does not exist on cloud environments. 
Can we get updated instructions for cloud?

**Comment by bohnertchris** [comment]
Looks like the UI changed. Thanks for catching this, @alisonasanchez. We will make the necessary updates.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit 65c8f73.
