### ISSUE TITLE
Document MSM

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#71]
The MSM is not documented yet below https://experienceleague.adobe.com/docs/experience-manager-cloud-service/sites/administering/

There should be a page similar to https://experienceleague.adobe.com/docs/experience-manager-65/administering/introduction/msm.html?lang=en#introduction which must outline particulary how to deal with the limitations of maintaining MSM blueprint and rollout configurations in the UI (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/release-notes/aem-cloud-changes.html?lang=en#apps-libs-immutable).

**Comment by aheim0** [comment]
Thanks for highlighting this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17355.

**Comment by bohnertchris** [comment]
MSM and translation documentation is now part of the AEMaaCS documentation set. See commit 1913b7a.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/sites/administering/reusing-content/msm-and-translation.html
