### ISSUE TITLE
Mixup of profiles and groups

### ISSUE THREAD

**Issue by ackoch** [AdobeDocs/experience-manager-cloud-service.en#72]
Issue in ./help/journey-onboarding/user-groups.md

We ask to create a "profile"  and then ask to add users to the "group". That's a bit confusing. And actually we are adding users to the "profile".

**Comment by bohnertchris** [comment]
Thanks for pointing out this inconsistency, @ackoch. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This has been corrected with commit 8049e6f.
