### ISSUE TITLE
Invalid link for "5 Steps to efficiently translate metadata."

### ISSUE THREAD

**Issue by johnb4** [AdobeDocs/experience-manager-cloud-service.en#75]
Issue in ./help/assets/translate-assets.md

The link for "5 Steps to efficiently translate metadata." points to a non-existent page.

**Comment by anujkapo** [comment]
Thanks, @johnb4. We will fix it.

**Comment by anujkapo** [comment]
Tracked with CQDOC-17407.

**Comment by ashishguptaiitb** [comment]
Thanks @johnb4 . I've removed the broken link.
