### ISSUE TITLE
Cloud manager for environment variables

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#76]
This document should talk about the cloud manager interface for setting environment variables. I'm curious how this would differ from the API and command line method. The doc for that is here:
https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/environment-variables.html?lang=en

The cloud manager method should also be suggested here (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/security/oauth2-support-for-mail-service.html?lang=en#integration-with-aem-as-a-cloud-service  Step 6), if appropriate, instead of just saying to use the API since using cloud manager would be much more simple.

Issue in ./help/implementing/deploying/configuring-osgi.md
Label: DocBugBlitz2023

**Comment by alisonasanchez** [comment]
Also, this note should be rewritten - I think it was meant to say user and not used: NOTE
Ensure that the used Cloud Manager API has assigned the role “Deployment Manager - Cloud Service”. Other roles are not able to execute all below commands.

maybe this would be better: 
You must be a member of Deployment Manager - Cloud Service" role to use this the Cloud Manager API. Other roles are not able to execute all below commands.

**Comment by alisonasanchez** [comment]
This is not valid json since the starting bracket is facing the wrong direction: 
]
        {
                "name" : "MY_VAR1",
                "value" : "plaintext value",
                "type" : "string"  <---default
        },
        {
                "name" : "MY_VAR2",
                "value" : "<secret value>",
                "type" : "secretString"
        }
]

Also, probably best to remove the <---default so that it is not copied and pasted. You can add a note saying that the default is string somewhere else.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This has been addressed with commit 235f2a9.
