### ISSUE TITLE
Ambiguous reference in documentation -  PaaS or SaaS?

### ISSUE THREAD

**Issue by juvestig** [AdobeDocs/experience-manager-cloud-service.en#76]
Issue in ./help/assets/overview.md
The first line here mentions this is PaaS solution. However, on this page (https://experienceleague.adobe.com/docs/experience-manager-cloud-service/overview/what-is-new-and-different.html?lang=en#aem-sites), under AEM Assets, it says its a SaaS solution.

**Comment by anujkapo** [comment]
Thanks, @juvestig for pointing this out. We will fix the contradicting statements.

**Comment by anujkapo** [comment]
Tracked with CQDOC-17409.

**Comment by ashishguptaiitb** [comment]
Thanks @juvestig . I've fixed it.
