### ISSUE TITLE
XF export to target does not work with IMS cloud service integration

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-cloud-service.en#77]
Issue in ./help/sites-cloud/integrating/integration-adobe-target-ims.md

According to SITES-4801, XF export to target does not work with IMS cloud service integration.
Doc needs to be updated with information suggesting to use legacy target configuration

**Label: DocBugBlitz2023**

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
This is already documented on:

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/sites/integrations/experience-fragments-target.html?lang=en
