### ISSUE TITLE
Development Guidelines should include a section for new asset APIs

### ISSUE THREAD

**Issue by kaushalmall** [AdobeDocs/experience-manager-cloud-service.en#79]
Issue in ./help/implementing/developing/introduction/development-guidelines.md

There is no mention of assets related best practices on this document. https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/admin/developer-reference-material-apis.html?lang=en#use-cases-and-apis explains a lot of use cases and corresponding tools/apis to use. Can we please add an "Assets best practices" section and point to the link above?

**Comment by mgulati1** [comment]
Added a section in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/development-guidelines.html.
