### ISSUE TITLE
There should be an explicit NOTE that Custom Domains are only applicable non-BYOCDN

### ISSUE THREAD

**Issue by somarc** [AdobeDocs/experience-manager-cloud-service.en#8]
Issue in ./help/implementing/cloud-manager/custom-domain-names/introduction.md

There should be an explicit NOTE that clarifies that Custom Domains are only applicable when Fastly is going to be the primary CDN. If a customer is BYOCDN they should NOT be configuring domains here. They would be entirely managed with the 3rd party CDN.

**Comment by bohnertchris** [comment]
Thanks for creating this issue, @somarc. We will review.

**Comment by bohnertchris** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Tracked with CQDOC-19608
