### ISSUE TITLE
No official support for the Sandbox programs

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-cloud-service.en#80]
Issue in ./help/implementing/cloud-manager/getting-access-to-aem-in-cloud/introduction-sandbox-programs.md

Issue Description:
Please add the following to the Restrictions and Conditions section.

### No technical support
Sandbox programs are not subject to support service.

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected in commit cb85196.
