### ISSUE TITLE
CIF Classic is no longer supported

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/experience-manager-cloud-service.en#80]
Issue in ./help/release-notes/aem-cloud-changes.md

It is crucial to understand that the old Commerce Integration Framework is no longer supported (https://experienceleague.adobe.com/docs/experience-manager-65/deploying/ecommerce/ecommerce.html?lang=en#ecommerce) but only Client-Side integration via GraphQL.

**Comment by guillaumecarlino** [comment]
Should be covered by [Notable Changes to the Commerce Integration Framework (CIF) Add-on](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content-and-commerce/changes.html)
