### ISSUE TITLE
Limitations for custom domains

### ISSUE THREAD

**Issue by ysawada-a** [AdobeDocs/experience-manager-cloud-service.en#81]
Issue in ./help/implementing/cloud-manager/custom-domain-names/introduction.md

Issue Description:
The items in Limitations section needs to be reordered and updated so that readers do not confuse wildcard domains with wildcard certificates.

Current:
- Custom domain names are supported in Cloud Manager for both publish and preview Services for Sites programs. Custom domains on the author side are not supported.
- Each Cloud Manager Environment can host up to a maximum of 500 custom domains per environment.
- AEM as a Cloud Service does not support wildcard domains.
- Before adding a custom domain name, a valid SSL certificate that contains the custom domain name must be installed for your program. Refer to Adding an SSL Certificate to learn more.
- Domain names cannot be added to environments while there is a current running pipeline attached to those environments.
- Only one domain name can be added at a time.
- The same domain name cannot be used on more than one environment.

Suggestion:
- Custom domain names are supported in Cloud Manager for both publish and preview Services for Sites programs. Custom domains on the author side are not supported.
- Each Cloud Manager Environment can host up to a maximum of 500 custom domains per environment.
- Domain names cannot be added to environments while there is a current running pipeline attached to those environments.
- **The same domain name cannot be used on more than one environment.**
- **Only one domain name can be added at a time. Wildcard domains are not supported in Cloud Manager. The custom domain name like \*.example.com cannot be added.**
- **Before adding a custom domain name, a valid SSL certificate that contains the custom domain name must be installed for your program. Wildcard certificates are valid. Refer to Adding an SSL Certificate to learn more.**

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This was corrected with commit fd72402.
