### ISSUE TITLE
Assets related changes doesn't mention that sub asset extraction doesn't exist in Cloud Service

### ISSUE THREAD

**Issue by kaushalmall** [AdobeDocs/experience-manager-cloud-service.en#82]
Issue in ./help/release-notes/aem-cloud-changes.md

Asset Handling and Delivery section doesn't mention that we don't support sub-asset extraction in Cloud Service, it should be added.

**Comment by aheim0** [comment]
Thanks for raising this - we will contact the appropriate group.

**Comment by aheim0** [comment]
Tracked with CQDOC-17480.

**Comment by ashishguptaiitb** [comment]
@kaushalmall I've made the updates (including the ones shared on the internal ticket) in this article about differences and parity:  https://experienceleague.adobe.com/docs/experience-manager-cloud-service/assets/assets-cloud-changes.html#asset-ingestion

Shall continue to update it based on the suggestions shared in the ticket. Closing this specific request.
