### ISSUE TITLE
Upload or download packages may fail under network timeout limitation in AEM as a Cloud Service

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-cloud-service.en#82]
Issue in ./help/implementing/developing/tools/package-manager.md

Issue Description:
It is reccomended to avoid making large size packages.
When you upload or download large size packages, it may fail according to network timeout.
The acceptable size is determined by users' network condition. You should test it to check if it is successful. Please use multiple packages by dividing paths included in one packages if it is necessary.

Label: DocBugBlitz2023

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Thank you for the suggestion, @nobhashim. Guidance has been added to the documentation regarding package sizes in commit cb29cb1.
