### ISSUE TITLE
Not possible to use Trace Dispatcher Level on AEM as a Cloud Service

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-cloud-service.en#83]
Issue in ./help/implementing/developing/introduction/logging.md

It's not possible to set Dispatcher Log Level to trace1 in AEM as a Cloud Service. You will get a ERROR: '11 CUSTOMER Excessive log level' exception in case you try to deploy.

**Label: DocBugBlitz2023**

**Comment by bohnertchris** [comment]
Thank you for reporting, but there is already CQDOC-19651 addressing this issue.
