### ISSUE TITLE
SDI is currently not supported by Fastly CDN configuration

### ISSUE THREAD

**Issue by sqdang** [AdobeDocs/experience-manager-cloud-service.en#84]
Issue in ./help/implementing/dispatcher/cdn.md

The customers configured SDI with include type SSI for local development and it worked as expected, Team then enabled the SDI configuration with include type ESI for Cloud environments where Fastly CDN is enabled. But at Adobe this is not enabled by default and the alternative suggested for the customer is they should bring their own CDN. This should be documented here. 

Label: DocBugBlitz2023

**Comment by bohnertchris** [comment]
This issue is not fully qualified.
