### ISSUE TITLE
Sandbox URLS don't work

### ISSUE THREAD

**Issue by davidjgonzalez** [AdobeDocs/experience-manager-cloud-service.en#86]
Issue in ./help/forms/summit-2023-workbook.md

This page lists a number of Sandboxes under Prerequisites, but none of them seem to work.

These should either be removed or updated to working sandboxes.

**Comment by bohnertchris** [comment]
Thank you for reporting this, @davidjgonzalez. But since the page is not indexed or included in the ToC, I am closing this since this page is a WIP based on Summit content.
