### ISSUE TITLE
MSM Custom Rollout Config - Dead Link to Missing Info

### ISSUE THREAD

**Issue by bstopp** [AdobeDocs/experience-manager-cloud-service.en#88]
Issue in ./help/sites-cloud/administering/msm/live-copy-sync-config.md

Under Rollout Configurations there is an anchor to `create a new rollout configuration`. This location doesn't exist.

(Paragraph for context)

> The following table lists the rollout configurations that are provided out-of-the-box with AEM. The table includes the trigger and synchronization actions of each rollout configuration. If the installed rollout configuration actions do not meet your requirements, you can create a new rollout configuration.

The link is supposed to lead to how to create a custom MSM Rollout Configuration. That info isn't to be found.

**Comment by bohnertchris** [comment]
Thanks for reporting this, @bstopp. We will review.

CQDOC-17645

**Comment by bohnertchris** [comment]
The documentation about creating one's own rollout configuration is still a work in progress to be migrated to the AEMaaCS documentation set. In the meantime I have commented out the link to that content.

Fixed in commit 832be9e.
