### ISSUE TITLE
graphiql does not work, at least with M1 Mac

### ISSUE THREAD

**Issue by nutmix** [AdobeDocs/experience-manager-cloud-service.en#89]
Issue in ./help/assets/content-fragments/graphql-api-content-fragments.md

I installed graphiql exactly as per instructions.  here is a rundown of the steps:

1. install fresh aem cloud sdk locally and run it.
2. download latest wknd from here: https://github.com/adobe/aem-guides-wknd
3. Fix the broken build (for M1 macs) by editing the root pom.xml and changing the frontend-maven-plugin to 1.11.0.
4. run mvn clean install -PautoInstallSinglePackage
5. verify aem site works by logging into http://localhost:4502/sites.html/content/wknd/us
6. verify graphql endpoint is configured and CORS is configured correctly (see screen shots)
7. installed graphiql package in package manager from https://experience.adobe.com/#/downloads/content/software-distribution/en/aemcloud.html?package=/content/software-distribution/en/details.html/content/dam/aemcloud/public/aem-graphql/graphiql-0.0.6.zip
8. verified package installed (see screen shot)
9. try to access http://localhost:4502/content/graphiql.html
10. get the below error response.

![image](https://user-images.githubusercontent.com/5080942/112599717-9841c480-8e10-11eb-80ed-7ec0438a080c.png)

![image](https://user-images.githubusercontent.com/5080942/112599803-ae4f8500-8e10-11eb-9264-cccf537d0752.png)

![image](https://user-images.githubusercontent.com/5080942/112599963-df2fba00-8e10-11eb-8184-6ce097def11f.png)

`Request Progress:

      0 TIMER_START{Request Processing}
      4 COMMENT timer_end format is {<elapsed microseconds>,<timer name>} <optional message>
     21 LOG Method=GET, PathInfo=null
     27 TIMER_START{handleSecurity}
   1584 TIMER_END{1555,handleSecurity} authenticator org.apache.sling.auth.core.impl.SlingAuthenticator@5e5d7787 returns true
   1866 TIMER_START{ResourceResolution}
   1977 TIMER_END{109,ResourceResolution} URI=/content/graphiql.html resolves to Resource=JcrNodeResource, type=graphql/components/graphiql, superType=null, path=/content/graphiql
   1986 LOG Resource Path Info: SlingRequestPathInfo: path='/content/graphiql', selectorString='null', extension='html', suffix='null'
   1986 TIMER_START{ServletResolution}
   1989 TIMER_START{resolveServlet(/content/graphiql)}
   2008 TIMER_END{17,resolveServlet(/content/graphiql)} Using servlet org.apache.sling.servlets.get.DefaultGetServlet
   2011 TIMER_END{24,ServletResolution} URI=/content/graphiql.html handled by Servlet=org.apache.sling.servlets.get.DefaultGetServlet
   2017 LOG Applying Requestfilters
   2069 LOG Calling filter: com.adobe.granite.resourceresolverhelper.impl.ResourceResolverHelperImpl
   2085 LOG Calling filter: org.apache.sling.security.impl.ContentDispositionFilter
   2091 LOG Calling filter: com.adobe.granite.csrf.impl.CSRFFilter
   2100 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   2105 LOG Calling filter: com.adobe.granite.httpcache.impl.InnerCacheFilter
   2118 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
   2124 LOG Calling filter: com.adobe.cq.history.impl.HistoryRequestFilter
   2405 LOG Calling filter: com.day.cq.wcm.core.impl.WCMRequestFilter
   2429 LOG Calling filter: com.adobe.cq.wcm.core.components.internal.servlets.CoreFormHandlingServlet
   2437 LOG Calling filter: com.adobe.granite.optout.impl.OptOutFilter
   2448 LOG Calling filter: com.day.cq.wcm.foundation.forms.impl.FormsHandlingServlet
   2458 LOG Calling filter: com.adobe.cq.wcm.core.extensions.amp.internal.AmpModeForwardFilter
   2664 LOG Calling filter: com.day.cq.dam.core.impl.servlet.DisableLegacyServletFilter
   2673 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
   2678 LOG Calling filter: com.day.cq.wcm.mobile.core.impl.redirect.RedirectFilter
   2685 LOG Calling filter: com.day.cq.wcm.core.impl.AuthoringUIModeServiceImpl
   2882 LOG Calling filter: com.adobe.granite.rest.assets.impl.AssetContentDispositionFilter
   2891 LOG Calling filter: com.adobe.granite.requests.logging.impl.RequestLoggerImpl
   2907 LOG Calling filter: com.adobe.granite.rest.impl.servlet.ApiResourceFilter
   2951 LOG Calling filter: com.day.cq.dam.core.impl.servlet.ActivityRecordHandler
   2969 LOG Calling filter: com.day.cq.dam.core.impl.assetlinkshare.AdhocAssetShareAuthHandler
   2978 LOG Calling filter: com.day.cq.wcm.core.impl.warp.TimeWarpFilter
   2993 LOG Applying Componentfilters
   2996 LOG Calling filter: com.day.cq.personalization.impl.TargetComponentFilter
   3001 LOG Calling filter: com.day.cq.wcm.core.impl.page.PageLockFilter
   3007 LOG Calling filter: com.day.cq.wcm.core.impl.WCMComponentFilter
   3149 LOG Calling filter: com.day.cq.wcm.core.impl.monitoring.PageComponentRequestFilter
   3154 LOG Calling filter: com.day.cq.wcm.core.impl.WCMDebugFilter
   3163 TIMER_START{org.apache.sling.servlets.get.DefaultGetServlet#0}
   3177 LOG No renderer for extension html
   3198 LOG Applying Error filters
   3200 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
   3203 LOG Calling filter: org.apache.sling.rewriter.impl.RewriterFilter
   3212 TIMER_START{handleError:status=404}
   3241 TIMER_END{27,handleError:status=404} Using handler BundledScriptServlet (/libs/sling/servlet/errorhandler/404.jsp)
   5984 LOG Found processor for post processing ProcessorConfiguration: {contentTypes=[text/html], order=-1, active=true, valid=true, processErrorResponse=true, pipeline=(generator=Config(type=htmlparser, config={}), transformers=(Config(type=linkchecker, config={}), Config(type=mobile, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobile: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=mobiledebug, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-mobiledebug: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), Config(type=contentsync, config=JcrPropertyMap [node=Node[NodeDelegate{tree=/libs/cq/config/rewriter/default/transformer-contentsync: { jcr:primaryType = nt:unstructured, component-optional = true}}], values={jcr:primaryType=nt:unstructured, component-optional=true}]), serializer=Config(type=htmlwriter, config={}))}
   6278 TIMER_END{6276,Request Processing} Dumping SlingRequestProgressTracker Entries`

**Comment by bohnertchris** [comment]
Hello @nutmix . Thank you for taking time to create an issue. However this sounds like a bug report since you are reporting seeing behavior different than expected in AEM. This is a repository for issues with the documentation. Please consider creating a customer care issue to report an issue with AEM itself.

https://helpx.adobe.com/contact/enterprise-support.ec.html

**Comment by nutmix** [comment]
Hi, thanks for the update.  I assume that graphql does work, but that there is some missing documentation or steps for the M1, or maybe something has changed and now the documentation is not correct.  I have raised this issue on the forms and got no response.

**Comment by bohnertchris** [comment]
Hello @nutmix. This documentation is very recent and I double-checked its accuracy using the latest Quickstart, WKND, and GraphiQL packages.

As suggested before, I encourage you to open a support issue with customer care. We appreciate you taking the time to create a documentation issue, and the forums can be a great assistance for special use cases, however customer care is there to offer direct support for errors with standard AEM functionality that you encounter.

**Comment by aheim0** [comment]
Two weeks have passed, so assume a support issue has been raised, so closing this issue.
