### ISSUE TITLE
Invalid links at User Sync Tool

### ISSUE THREAD

**Issue by ysawada-a** [AdobeDocs/experience-manager-cloud-service.en#89]
Issue in ./help/security/ims-support.md

Issue Description:
There are invalid links at User Sync Tool section:
- More information about the new group features can be found at this location(https://github.com/adobe-apiplatform/user-sync.py/blob/v2/docs/en/user-manual/advanced_configuration.md#additional-group-options). -> Not found
- Adobe I/O Console Documentation can be found here(https://www.adobe.io/apis/cloudplatform/console.html). -> Not found
- The User Management API that is used by the User Sync Tool is covered here(https://www.adobe.io/apis/cloudplatform/umapi-new.html). -> Not found

Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @ysawada-a. We will fix them.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by TylerRush** [comment]
Thanks for your feedback on the documentation. The broken links have been corrected. The changes are in the pipeline and will appear on Experience League shortly.
