### ISSUE TITLE
Information on Permissions Required

### ISSUE THREAD

**Issue by alisonasanchez** [AdobeDocs/experience-manager-cloud-service.en#90]
Issue in ./help/implementing/cloud-manager/managing-ssl-certifications/add-ssl-certificate.md
There needs to be information on this page that explains what permissions are needed to perform the action.

Label:DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @alisonasanchez. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
This information is already part of the cited page.

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/manage-ssl-certificates/add-ssl-certificate.html#adding-a-cert

> A user must be a member of the Business Owner or Deployment Manager role to install an SSL certificate in Cloud Manager.
