### ISSUE TITLE
Example link points to non-existent page in documentation

### ISSUE THREAD

**Issue by Rampai94** [AdobeDocs/experience-manager-cloud-service.en#90]
Hi All,

The documentation for [Dispatcher Cache Invalidation](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/caching.html?lang=en#disp) points to a non-existent link.

The broken link is API example page. PFA.

![Screenshot (94)](https://user-images.githubusercontent.com/22491984/113332385-bb9fce80-933e-11eb-88e7-9f4278371a45.png)

Request someone to send the example page for configuring caching in AEMaaCS.

Thanks,
Ram

**Comment by anujkapo** [comment]
Thanks, @Rampai94. We will fix it.

**Comment by anujkapo** [comment]
Tracked using CQDOC-17683.

**Comment by aheim0** [comment]
Unfortunately that page is out of date, so we have removed the link. We will open a new issue to provide a new example.
Closing this issue.
