### ISSUE TITLE
The Handler Advance box needs to be checked for the workflow execution not to remain in a waiting state

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-cloud-service.en#91]
Issue in ./help/operations/replication.md

"Click on the Process tab and select Publish Content Tree from the drop down list" should be updated to 

"Click on the Process tab and select Publish Content Tree from the drop down list and check the handler advance check box".
The  image should also be updated accordingly.

Reference: https://cq-dev.slack.com/archives/CAHGY76MS/p1681732416371589
                  GRANITE-45191

**Label: DocBugBlitz2023**

**Comment by anujkapo** [comment]
Thanks, @rnituadobe. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by sarchiz** [comment]
Hi @rnituadobe - we've updated the docs and the accompanying screenshot. Thanks for reporting this.
