### ISSUE TITLE
Clarify behaviour changes when customer CDN points at AEM managed CDN

### ISSUE THREAD

**Issue by jwadolowski** [AdobeDocs/experience-manager-cloud-service.en#92]
[This page](https://github.com/AdobeDocs/experience-manager-cloud-service.en/blob/master/help/implementing/dispatcher/cdn.md#customer-cdn-points-to-aem-managed-cdn-point-to-point-cdn) lists a set of requirements to support customer CDN in front AEM managed CDN, but doesn't mention any implications of such configuration. 

In the most trivial setup customer CDN will act as a caching proxy and treat AEM CDN as an origin.

![customer_cdn](https://user-images.githubusercontent.com/6334715/113723755-f49ac300-96f1-11eb-8f53-6cc61f5a729f.jpeg)

Here's what I mean:

> Set the X-Forwarded-Host header with the domain name.

The browser doesn't do that and everything works out of the box (when customer CDN is not involved), so why my CDN has to do it? `X-Forwarded-Host` may impact Sling mappings, but since your CDN is a black box that's just a blind guess.

> Set Host header with the origin domain, which is the AEM CDN’s ingress. The value should come from Adobe.

What's "origin domain" in this context? Is that `publish-p<PROGRAM_ID>-e<ENV-ID>.adobeaemcloud.com` (which points to AEM CDN) or dispatcher/publish origin URL (you can't see it by default)? "The value should come from Adobe" sentence suggests the latter, but at the same time the page header says "Customer CDN points to AEM Managed CDN", which I find super confusing.

> Send the SNI header to the origin. Like the Host header, the SNI header must be the origin domain.

That's yet another point I scratch my head at. Origin domain may indicate you're bypassing AEM managed CDN, which stays in contradiction to what docs say unless "origin domain" means "AEM managed CDN".

> Set either the X-Edge-Key or the X-AEM-Edge-Key (if your CDN strips X-Edge-*), which is needed to route traffic correctly to the AEM servers. The value should come from Adobe. Please inform Adobe if you want direct access to Adobe CDN’s ingress (to be blocked when X-Edge-Key is not present).

Again, why's that required? Since you can't truly bypass AEM managed CDN I'd expect that your CDN takes care of those headers if they're needed for whatever reason.

---

On top of that, what are the benefits of configuring [custom domain name](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/using-cloud-manager/custom-domain-names/add-custom-domain-name.html?lang=en#using-cloud-manager) and [TLS certificate](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/using-cloud-manager/manage-ssl-certificates/add-ssl-certificate.html?lang=en#important-considerations) when you can't disable default `*.adobeaemcloud.com` endpoint (see [this](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/using-cloud-manager/custom-domain-names/introduction.html?lang=en#using-cloud-manager))? I refer to a setup as outlined on the diagram attached above.

Thanks,
Jakub

**Comment by TylerRush** [comment]
CQDOC-17702

**Comment by raimanS** [comment]
The page at [1] has been updated to clarify the guidelines.

[1] - https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/cdn.html#point-to-point-CDN

**Comment by jwadolowski** [comment]
@TylerRush @raimanS @bohnertchris thanks for the update.

Is this expected that https://github.com/AdobeDocs/experience-manager-cloud-service.en/blob/master/help/implementing/dispatcher/cdn.md is not in sync with https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/cdn.html#content-delivery? I thought that this Git repo is the single source of truth.
