### ISSUE TITLE
Copies of OOTB workflow models cannot be edited

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-cloud-service.en#92]
Issue in ./help/operations/replication.md

"Do not modify or invoke the original model. Instead, make sure to first copy the model and then modify or invoke that copy."

The above statement is incorrect it is not possible to modify the copy of the model so please change 
 
"You can trigger a tree replication by choosing Tools - Workflow - Models and copying the Publish Content Tree out-of-the-box workflow model, as shown below: Do not modify or invoke the original model. Instead, make sure to first copy the model and then modify or invoke that copy."

to

"You can trigger a tree replication by choosing Tools - Workflow - Models and copying the Publish Content Tree out-of-the-box workflow model, as shown below: Do not invoke the original model. Instead, make sure to first copy the model and then invoke that copy."

Label: DocBugBlitz2023

**Comment by rnituadobe** [comment]
Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @rnituadobe. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Changes have been made, and published.
Closing this issue.
