### ISSUE TITLE
Wrong Touch UI Configuration path

### ISSUE THREAD

**Issue by rnituadobe** [AdobeDocs/experience-manager-cloud-service.en#93]
Issue in ./help/sites-cloud/integrating/integrating-adobe-target.md

Touch UI interface creates the configuration below "../cloudconfigs/target" but the document has the path "/conf/tenant/settings/cloudservices/target/"
It should be "/conf/tenant/settings/cloudconfigs/target/" refer [0]

[0] https://git.corp.adobe.com/CQ/integration-target/blob/0a30a726786177dd681d0337a57a828ced54f501/bundles/cq-target-integration/src/main/java/com/day/cq/analytics/testandtarget/impl/util/ConfigurationUtils.java#L71

Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @rnituadobe. We'll fix it.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by TylerRush** [comment]
Thank you for your feedback. I changed /conf/tenant/settings/cloudservices/target/ to /conf/tenant/settings/cloudconfigs/target/ under the Touch UI section of the table. The changes are in the pipeline and will appear on Experience League shortly.
