### ISSUE TITLE
Creating a Live Copy may fail under network timeout limitation in AEM as a Cloud Service

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-cloud-service.en#95]
Issue in ./help/sites-cloud/administering/msm/creating-live-copies.md

Issue Description:

Please add the folloing note to the bottom of "Creating a Live Copy" section.

An error dialog may appear with the message "Fail to submit the form" This happens due to a network timeout.
But the process to create the live copy is going on. Please check the pages of the live copy after a while.

Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @nobhashim. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by TylerRush** [comment]
Thank you for your feedback. I have added the note to the documentation page. The changes are in the pipeline and will be published to Experience League shortly.
