### ISSUE TITLE
No mention of Custom Monitoring being add-ons

### ISSUE THREAD

**Issue by nobhashim** [AdobeDocs/experience-manager-cloud-service.en#96]
Issue in ./help/operations/monitoring.md

Issue Description:

There is no explanation about the requirement to qualify for Advanced Cloud Support Add-ons when receiving the Custom Monitoring service offering as part of External Availability. That would be misleading customers into thinking that the service is available unconditionally. Therefore, please change as follows.

Current:
With Custom monitoring, customers have the option to provide up to five distinct web property URLs prior to going live. These URLs should be valid and return an HTTP 200 response code. These monitors support customers who bring their own CDN in front of the Adobe CDN and any external traffic routing employed in front of AEM as a Cloud Service that is not under Adobe’s control. Alerts resulting from Custom Monitoring checks will engage Adobe’s support teams and processes.

Suggestion:
With Custom monitoring, customers have the option to provide up to five distinct web property URLs prior to going live. These URLs should be valid and return an HTTP 200 response code. These monitors support customers who bring their own CDN in front of the Adobe CDN and any external traffic routing employed in front of AEM as a Cloud Service that is not under Adobe’s control. Alerts resulting from Custom Monitoring checks will engage Adobe’s support teams and processes.
Custom Monitoring requires Advanced Cloud Support via add-ons.

Label: DocBugBlitz2023

**Comment by anujkapo** [comment]
Thanks, @nobhashim. We will take a look.

**Comment by anujkapo** [comment]
@adobe export issue to Jira project CQDOC

**Comment by TylerRush** [comment]
As a result of this discussion, the following page has been updated:

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/operations/monitoring.html?lang=en#custom-monitoring
