### ISSUE TITLE
Typo in undoing an index section

### ISSUE THREAD

**Issue by kaushalmall** [AdobeDocs/experience-manager-cloud-service.en#98]
Issue in ./help/operations/indexing.md
![image](https://user-images.githubusercontent.com/4323558/114775437-26311100-9d26-11eb-8b4d-c724db075b09.png)

it should be damAssetLucene, not damAssetAssetLucene

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-17745.

**Comment by ashishguptaiitb** [comment]
Thanks @kaushalmall . Good catch. This is updated now.
I also checked in 6.x docs and this typo does not exist.
