### ISSUE TITLE
Notifications for Cloud manager updates

### ISSUE THREAD

**Issue by anusaxen** [AdobeDocs/experience-manager-cloud-service.en#98]
Issue Description:
There are notifications for AEM Push Updates, maintenance updates, Pipeline executions. But there is no way for customer to know the Cloud manager version , when the last update to Cloud manager itself was done etc.

Use case - We had a P1 sometime back where customer mentioned that the previous code that was deployed didn't work when executed again. During investigation it was identified that it was the same commit and customer did not change anything.

Only change was in cloud manager update at that time . And there was no way to check what is the Cloud manager version , whether any updates were pushed for customer or not ... so if there is a way to identify the version of cloud manager itself shown .. customers/support can verify what features are available or not available

Label: DocBugBlitz2023

**Comment by TylerRush** [comment]
Thanks @anusaxen. We will investigate this issue.

**Comment by TylerRush** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
In the past the release number was not surfaced in the release notes. For several months now, however, the release notes include the release number. This number correlates directly with the AEM release information that is shown on the Environments tab of every program. As far as I can tell, this has solved the issue. If you believe there are further changes needed, please clarify them in a new issue.
