### ISSUE TITLE
Adobe Relic documentation for clarity on what is supported out of the box by New Relic that comes with Adobe

### ISSUE THREAD

**Issue by s-aryal** [AdobeDocs/experience-manager-cloud-service.en#99]
Issue in ./help/implementing/cloud-manager/user-access-new-relic.md

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by bohnertchris** [comment]
Hello. The cited document already has sections for

- Features
- What does Adobe monitor with new Relic One
- Limitations

Along with additional FAQs. I am not clear on what is missing. Could you please elaborate what you are expecting to find in this documentation which is not already represented?

Thanks

**Comment by bohnertchris** [comment]
I am closing this issue due to lack of response. If you still have suggestions for this documentation, please create a new issue with detail on the changes you would like to see.
